// Code generated by ogen, DO NOT EDIT.

package api

import "github.com/ogen-go/ogen/validate"

// Equal compares two FeedbackScore instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a FeedbackScore) Equal(b FeedbackScore, depth int) bool {
	if depth > 10 {
		panic(&validate.DepthLimitError{
			MaxDepth: 10,
			TypeName: "FeedbackScore",
		})
	}

	if a.Name != b.Name {
		return false
	}
	// Compare optional field: CategoryName
	if a.CategoryName.Set != b.CategoryName.Set {
		return false
	}
	if a.CategoryName.Set {
		if a.CategoryName.Value != b.CategoryName.Value {
			return false
		}
	}
	if a.Value != b.Value {
		return false
	}
	// Compare optional field: Reason
	if a.Reason.Set != b.Reason.Set {
		return false
	}
	if a.Reason.Set {
		if a.Reason.Value != b.Reason.Value {
			return false
		}
	}
	if a.Source != b.Source {
		return false
	}
	// Compare optional field: CreatedAt
	if a.CreatedAt.Set != b.CreatedAt.Set {
		return false
	}
	if a.CreatedAt.Set {
		if a.CreatedAt.Value != b.CreatedAt.Value {
			return false
		}
	}
	// Compare optional field: LastUpdatedAt
	if a.LastUpdatedAt.Set != b.LastUpdatedAt.Set {
		return false
	}
	if a.LastUpdatedAt.Set {
		if a.LastUpdatedAt.Value != b.LastUpdatedAt.Value {
			return false
		}
	}
	// Compare optional field: CreatedBy
	if a.CreatedBy.Set != b.CreatedBy.Set {
		return false
	}
	if a.CreatedBy.Set {
		if a.CreatedBy.Value != b.CreatedBy.Value {
			return false
		}
	}
	// Compare optional field: LastUpdatedBy
	if a.LastUpdatedBy.Set != b.LastUpdatedBy.Set {
		return false
	}
	if a.LastUpdatedBy.Set {
		if a.LastUpdatedBy.Value != b.LastUpdatedBy.Value {
			return false
		}
	}
	// Compare optional field: ValueByAuthor
	if a.ValueByAuthor.Set != b.ValueByAuthor.Set {
		return false
	}
	if a.ValueByAuthor.Set {
		if len(a.ValueByAuthor.Value) != len(b.ValueByAuthor.Value) {
			return false
		}
		for k, v := range a.ValueByAuthor.Value {
			if bv, ok := b.ValueByAuthor.Value[k]; !ok || v != bv {
				return false
			}
		}
	}
	return true
}
