// Code generated by ogen, DO NOT EDIT.
package api

type AddItemsToAnnotationQueueRes interface {
	addItemsToAnnotationQueueRes()
}

type AttachmentListRes interface {
	attachmentListRes()
}

type BatchUpdateDatasetItemsRes interface {
	batchUpdateDatasetItemsRes()
}

type BatchUpdateSpansRes interface {
	batchUpdateSpansRes()
}

type BatchUpdateThreadsRes interface {
	batchUpdateThreadsRes()
}

type BatchUpdateTracesRes interface {
	batchUpdateTracesRes()
}

type CheckAccessRes interface {
	checkAccessRes()
}

type CloseTraceThreadRes interface {
	closeTraceThreadRes()
}

type CompareDatasetVersionsRes interface {
	compareDatasetVersionsRes()
}

type CompleteMultiPartUploadRes interface {
	completeMultiPartUploadRes()
}

type CostsSummaryRes interface {
	costsSummaryRes()
}

type CreateAlertRes interface {
	createAlertRes()
}

type CreateAnnotationQueueBatchRes interface {
	createAnnotationQueueBatchRes()
}

type CreateAnnotationQueueRes interface {
	createAnnotationQueueRes()
}

type CreateDatasetItemsFromCsvRes interface {
	createDatasetItemsFromCsvRes()
}

type CreateDatasetVersionRes interface {
	createDatasetVersionRes()
}

type CreateProjectRes interface {
	createProjectRes()
}

type CreatePromptRes interface {
	createPromptRes()
}

type CreatePromptVersionRes interface {
	createPromptVersionRes()
}

type CreateSpanRes interface {
	createSpanRes()
}

type CreateVersionTagRes interface {
	createVersionTagRes()
}

type DeleteAlertBatchRes interface {
	deleteAlertBatchRes()
}

type DeleteAnnotationQueueBatchRes interface {
	deleteAnnotationQueueBatchRes()
}

type DeleteAttachmentsRes interface {
	deleteAttachmentsRes()
}

type DeleteDatasetItemsRes interface {
	deleteDatasetItemsRes()
}

type DeleteFeedbackDefinitionByIdRes interface {
	deleteFeedbackDefinitionByIdRes()
}

type DeleteFeedbackDefinitionsBatchRes interface {
	deleteFeedbackDefinitionsBatchRes()
}

type DeleteProjectByIdRes interface {
	deleteProjectByIdRes()
}

type DeleteSpanByIdRes interface {
	deleteSpanByIdRes()
}

type DeleteWorkspaceConfigurationRes interface {
	deleteWorkspaceConfigurationRes()
}

type EvaluateSpansRes interface {
	evaluateSpansRes()
}

type EvaluateThreadsRes interface {
	evaluateThreadsRes()
}

type EvaluateTracesRes interface {
	evaluateTracesRes()
}

type ExperimentItemsBulkRes interface {
	experimentItemsBulkRes()
}

type FindExperimentGroupsAggregationsRes interface {
	findExperimentGroupsAggregationsRes()
}

type FindExperimentGroupsRes interface {
	findExperimentGroupsRes()
}

type FindExperimentsRes interface {
	findExperimentsRes()
}

type FindOptimizationsRes interface {
	findOptimizationsRes()
}

type FindStudioOptimizationsRes interface {
	findStudioOptimizationsRes()
}

type FinishExperimentsRes interface {
	finishExperimentsRes()
}

type GetAlertByIdRes interface {
	getAlertByIdRes()
}

type GetAnnotationQueueByIdRes interface {
	getAnnotationQueueByIdRes()
}

type GetCostRes interface {
	getCostRes()
}

type GetDashboardByIdRes interface {
	getDashboardByIdRes()
}

type GetExperimentByIdRes interface {
	getExperimentByIdRes()
}

type GetExperimentItemByIdRes interface {
	getExperimentItemByIdRes()
}

type GetLlmProviderApiKeyByIdRes interface {
	getLlmProviderApiKeyByIdRes()
}

type GetMetricRes interface {
	getMetricRes()
}

type GetOptimizationByIdRes interface {
	getOptimizationByIdRes()
}

type GetProjectMetricsRes interface {
	getProjectMetricsRes()
}

type GetPromptByIdRes interface {
	getPromptByIdRes()
}

type GetPromptVersionByIdRes interface {
	getPromptVersionByIdRes()
}

type GetSpanByIdRes interface {
	getSpanByIdRes()
}

type GetSpanCommentRes interface {
	getSpanCommentRes()
}

type GetStudioOptimizationByIdRes interface {
	getStudioOptimizationByIdRes()
}

type GetStudioOptimizationLogsRes interface {
	getStudioOptimizationLogsRes()
}

type GetThreadCommentRes interface {
	getThreadCommentRes()
}

type GetTraceCommentRes interface {
	getTraceCommentRes()
}

type GetTraceThreadRes interface {
	getTraceThreadRes()
}

type GetWorkspaceConfigurationRes interface {
	getWorkspaceConfigurationRes()
}

type GetWorkspaceNameRes interface {
	getWorkspaceNameRes()
}

type ListDatasetVersionsRes interface {
	listDatasetVersionsRes()
}

type MetricsSummaryRes interface {
	metricsSummaryRes()
}

type PatchDatasetItemRes interface {
	patchDatasetItemRes()
}

type RemoveItemsFromAnnotationQueueRes interface {
	removeItemsFromAnnotationQueueRes()
}

type RestoreDatasetVersionRes interface {
	restoreDatasetVersionRes()
}

type RestorePromptVersionRes interface {
	restorePromptVersionRes()
}

type RetrieveProjectRes interface {
	retrieveProjectRes()
}

type RetrievePromptVersionRes interface {
	retrievePromptVersionRes()
}

type StartMultiPartUploadRes interface {
	startMultiPartUploadRes()
}

type StoreLlmProviderApiKeyRes interface {
	storeLlmProviderApiKeyRes()
}

type TestWebhookRes interface {
	testWebhookRes()
}

type UpdateAlertRes interface {
	updateAlertRes()
}

type UpdateAnnotationQueueRes interface {
	updateAnnotationQueueRes()
}

type UpdateDashboardRes interface {
	updateDashboardRes()
}

type UpdateDatasetVersionRes interface {
	updateDatasetVersionRes()
}

type UpdateExperimentRes interface {
	updateExperimentRes()
}

type UpdateLlmProviderApiKeyRes interface {
	updateLlmProviderApiKeyRes()
}

type UpdateProjectRes interface {
	updateProjectRes()
}

type UpdatePromptRes interface {
	updatePromptRes()
}

type UpdatePromptVersionsRes interface {
	updatePromptVersionsRes()
}

type UpdateSpanCommentRes interface {
	updateSpanCommentRes()
}

type UpdateSpanRes interface {
	updateSpanRes()
}

type UpdateThreadCommentRes interface {
	updateThreadCommentRes()
}

type UpdateThreadRes interface {
	updateThreadRes()
}

type UpdateTraceCommentRes interface {
	updateTraceCommentRes()
}

type UpsertWorkspaceConfigurationRes interface {
	upsertWorkspaceConfigurationRes()
}
