// Code generated by ogen, DO NOT EDIT.

package api

import "github.com/ogen-go/ogen/validate"

// Equal compares two Comment instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a Comment) Equal(b Comment, depth int) bool {
	if depth > 10 {
		panic(&validate.DepthLimitError{
			MaxDepth: 10,
			TypeName: "Comment",
		})
	}

	// Compare optional field: ID
	if a.ID.Set != b.ID.Set {
		return false
	}
	if a.ID.Set {
		if a.ID.Value != b.ID.Value {
			return false
		}
	}
	if a.Text != b.Text {
		return false
	}
	// Compare optional field: CreatedAt
	if a.CreatedAt.Set != b.CreatedAt.Set {
		return false
	}
	if a.CreatedAt.Set {
		if a.CreatedAt.Value != b.CreatedAt.Value {
			return false
		}
	}
	// Compare optional field: LastUpdatedAt
	if a.LastUpdatedAt.Set != b.LastUpdatedAt.Set {
		return false
	}
	if a.LastUpdatedAt.Set {
		if a.LastUpdatedAt.Value != b.LastUpdatedAt.Value {
			return false
		}
	}
	// Compare optional field: CreatedBy
	if a.CreatedBy.Set != b.CreatedBy.Set {
		return false
	}
	if a.CreatedBy.Set {
		if a.CreatedBy.Value != b.CreatedBy.Value {
			return false
		}
	}
	// Compare optional field: LastUpdatedBy
	if a.LastUpdatedBy.Set != b.LastUpdatedBy.Set {
		return false
	}
	if a.LastUpdatedBy.Set {
		if a.LastUpdatedBy.Value != b.LastUpdatedBy.Value {
			return false
		}
	}
	return true
}
