// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"hash/fnv"
)

// Hash computes a hash value for AnnotationQueueWrite using FNV-1a.
// Equal objects must produce equal hashes.
func (a AnnotationQueueWrite) Hash() uint64 {
	h := fnv.New64a()

	// Hash optional field: ID
	if a.ID.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.ID.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash primitive field: ProjectID
	h.Write([]byte(fmt.Sprintf("%v", a.ProjectID)))
	// Hash primitive field: Name
	h.Write([]byte(fmt.Sprintf("%v", a.Name)))
	// Hash optional field: Description
	if a.Description.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.Description.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash optional field: Instructions
	if a.Instructions.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.Instructions.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash primitive field: Scope
	h.Write([]byte(fmt.Sprintf("%v", a.Scope)))
	// Hash optional field: CommentsEnabled
	if a.CommentsEnabled.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.CommentsEnabled.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash array field: FeedbackDefinitionNames
	for _, item := range a.FeedbackDefinitionNames {
		h.Write([]byte(fmt.Sprintf("%v", item)))
	}
	return h.Sum64()
}
