// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"hash/fnv"
)

// Hash computes a hash value for Comment using FNV-1a.
// Equal objects must produce equal hashes.
func (a Comment) Hash() uint64 {
	h := fnv.New64a()

	// Hash optional field: ID
	if a.ID.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.ID.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash primitive field: Text
	h.Write([]byte(fmt.Sprintf("%v", a.Text)))
	// Hash optional field: CreatedAt
	if a.CreatedAt.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.CreatedAt.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash optional field: LastUpdatedAt
	if a.LastUpdatedAt.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.LastUpdatedAt.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash optional field: CreatedBy
	if a.CreatedBy.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.CreatedBy.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash optional field: LastUpdatedBy
	if a.LastUpdatedBy.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.LastUpdatedBy.Value)))
	} else {
		h.Write([]byte{0})
	}
	return h.Sum64()
}
