// Code generated by ogen, DO NOT EDIT.

package api

import "github.com/ogen-go/ogen/validate"

// Equal compares two AnnotationQueueWrite instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a AnnotationQueueWrite) Equal(b AnnotationQueueWrite, depth int) bool {
	if depth > 10 {
		panic(&validate.DepthLimitError{
			MaxDepth: 10,
			TypeName: "AnnotationQueueWrite",
		})
	}

	// Compare optional field: ID
	if a.ID.Set != b.ID.Set {
		return false
	}
	if a.ID.Set {
		if a.ID.Value != b.ID.Value {
			return false
		}
	}
	if a.ProjectID != b.ProjectID {
		return false
	}
	if a.Name != b.Name {
		return false
	}
	// Compare optional field: Description
	if a.Description.Set != b.Description.Set {
		return false
	}
	if a.Description.Set {
		if a.Description.Value != b.Description.Value {
			return false
		}
	}
	// Compare optional field: Instructions
	if a.Instructions.Set != b.Instructions.Set {
		return false
	}
	if a.Instructions.Set {
		if a.Instructions.Value != b.Instructions.Value {
			return false
		}
	}
	if a.Scope != b.Scope {
		return false
	}
	// Compare optional field: CommentsEnabled
	if a.CommentsEnabled.Set != b.CommentsEnabled.Set {
		return false
	}
	if a.CommentsEnabled.Set {
		if a.CommentsEnabled.Value != b.CommentsEnabled.Value {
			return false
		}
	}
	// Compare array field: FeedbackDefinitionNames
	if len(a.FeedbackDefinitionNames) != len(b.FeedbackDefinitionNames) {
		return false
	}
	for i := range a.FeedbackDefinitionNames {
		if a.FeedbackDefinitionNames[i] != b.FeedbackDefinitionNames[i] {
			return false
		}
	}
	return true
}
