// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddItemsToAnnotationQueue implements addItemsToAnnotationQueue operation.
//
// Add traces or threads to annotation queue.
//
// POST /v1/private/annotation-queues/{id}/items/add
func (UnimplementedHandler) AddItemsToAnnotationQueue(ctx context.Context, req OptAnnotationQueueItemIds, params AddItemsToAnnotationQueueParams) (r AddItemsToAnnotationQueueRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddSpanComment implements addSpanComment operation.
//
// Add span comment.
//
// POST /v1/private/spans/{id}/comments
func (UnimplementedHandler) AddSpanComment(ctx context.Context, req OptComment, params AddSpanCommentParams) (r *AddSpanCommentCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddSpanFeedbackScore implements addSpanFeedbackScore operation.
//
// Add span feedback score.
//
// PUT /v1/private/spans/{id}/feedback-scores
func (UnimplementedHandler) AddSpanFeedbackScore(ctx context.Context, req OptFeedbackScore, params AddSpanFeedbackScoreParams) error {
	return ht.ErrNotImplemented
}

// AddThreadComment implements addThreadComment operation.
//
// Add thread comment.
//
// POST /v1/private/traces/threads/{id}/comments
func (UnimplementedHandler) AddThreadComment(ctx context.Context, req OptComment, params AddThreadCommentParams) (r *AddThreadCommentCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddTraceComment implements addTraceComment operation.
//
// Add trace comment.
//
// POST /v1/private/traces/{id}/comments
func (UnimplementedHandler) AddTraceComment(ctx context.Context, req OptComment, params AddTraceCommentParams) (r *AddTraceCommentCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// AddTraceFeedbackScore implements addTraceFeedbackScore operation.
//
// Add trace feedback score.
//
// PUT /v1/private/traces/{id}/feedback-scores
func (UnimplementedHandler) AddTraceFeedbackScore(ctx context.Context, req OptFeedbackScore, params AddTraceFeedbackScoreParams) error {
	return ht.ErrNotImplemented
}

// AttachmentList implements attachmentList operation.
//
// Attachments list for entity.
//
// GET /v1/private/attachment/list
func (UnimplementedHandler) AttachmentList(ctx context.Context, params AttachmentListParams) (r AttachmentListRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BatchUpdateDatasetItems implements batchUpdateDatasetItems operation.
//
// Update multiple dataset items.
//
// PATCH /v1/private/datasets/items/batch
func (UnimplementedHandler) BatchUpdateDatasetItems(ctx context.Context, req OptDatasetItemBatchUpdate) (r BatchUpdateDatasetItemsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BatchUpdateSpans implements batchUpdateSpans operation.
//
// Update multiple spans.
//
// PATCH /v1/private/spans/batch
func (UnimplementedHandler) BatchUpdateSpans(ctx context.Context, req OptSpanBatchUpdate) (r BatchUpdateSpansRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BatchUpdateThreads implements batchUpdateThreads operation.
//
// Update multiple threads.
//
// PATCH /v1/private/traces/threads/batch
func (UnimplementedHandler) BatchUpdateThreads(ctx context.Context, req OptTraceThreadBatchUpdate) (r BatchUpdateThreadsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BatchUpdateTraces implements batchUpdateTraces operation.
//
// Update multiple traces.
//
// PATCH /v1/private/traces/batch
func (UnimplementedHandler) BatchUpdateTraces(ctx context.Context, req OptTraceBatchUpdate) (r BatchUpdateTracesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CancelStudioOptimizations implements cancelStudioOptimizations operation.
//
// Cancel Studio optimizations by id.
//
// GET /v1/private/optimizations/studio/{id}/cancel
func (UnimplementedHandler) CancelStudioOptimizations(ctx context.Context, params CancelStudioOptimizationsParams) error {
	return ht.ErrNotImplemented
}

// CheckAccess implements checkAccess operation.
//
// Check user access to workspace.
//
// POST /v1/private/auth
func (UnimplementedHandler) CheckAccess(ctx context.Context, req *AuthDetailsHolder) (r CheckAccessRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CloseTraceThread implements closeTraceThread operation.
//
// Close one or multiple trace threads. Supports both single thread_id and multiple thread_ids for
// batch operations.
//
// PUT /v1/private/traces/threads/close
func (UnimplementedHandler) CloseTraceThread(ctx context.Context, req OptTraceThreadBatchIdentifier) (r CloseTraceThreadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompareDatasetVersions implements compareDatasetVersions operation.
//
// Compare the latest committed dataset version with the current draft state. This endpoint provides
// insights into changes made since the last version was committed. The comparison calculates
// additions, modifications, deletions, and unchanged items between the latest version snapshot and
// current draft.
//
// GET /v1/private/datasets/{id}/versions/diff
func (UnimplementedHandler) CompareDatasetVersions(ctx context.Context, params CompareDatasetVersionsParams) (r CompareDatasetVersionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompleteMultiPartUpload implements completeMultiPartUpload operation.
//
// Complete multipart attachment upload.
//
// POST /v1/private/attachment/upload-complete
func (UnimplementedHandler) CompleteMultiPartUpload(ctx context.Context, req OptCompleteMultipartUploadRequest) (r CompleteMultiPartUploadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CostsSummary implements costsSummary operation.
//
// Get costs summary.
//
// POST /v1/private/workspaces/costs/summaries
func (UnimplementedHandler) CostsSummary(ctx context.Context, req OptWorkspaceMetricsSummaryRequest) (r CostsSummaryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAlert implements createAlert operation.
//
// Create alert.
//
// POST /v1/private/alerts
func (UnimplementedHandler) CreateAlert(ctx context.Context, req OptAlertWrite) (r CreateAlertRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAnnotationQueue implements createAnnotationQueue operation.
//
// Create annotation queue for human annotation workflows.
//
// POST /v1/private/annotation-queues
func (UnimplementedHandler) CreateAnnotationQueue(ctx context.Context, req OptAnnotationQueueWrite) (r CreateAnnotationQueueRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAnnotationQueueBatch implements createAnnotationQueueBatch operation.
//
// Create multiple annotation queues for human annotation workflows.
//
// POST /v1/private/annotation-queues/batch
func (UnimplementedHandler) CreateAnnotationQueueBatch(ctx context.Context, req OptAnnotationQueueBatchWrite) (r CreateAnnotationQueueBatchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAutomationRuleEvaluator implements createAutomationRuleEvaluator operation.
//
// Create automation rule evaluator.
//
// POST /v1/private/automations/evaluators
func (UnimplementedHandler) CreateAutomationRuleEvaluator(ctx context.Context, req OptAutomationRuleEvaluatorWrite) (r *CreateAutomationRuleEvaluatorCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateChatCompletions implements createChatCompletions operation.
//
// Create chat completions.
//
// POST /v1/private/chat/completions
func (UnimplementedHandler) CreateChatCompletions(ctx context.Context, req OptChatCompletionRequest) (r *ChatCompletionResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDashboard implements createDashboard operation.
//
// Create a new dashboard in a workspace.
//
// POST /v1/private/dashboards
func (UnimplementedHandler) CreateDashboard(ctx context.Context, req OptDashboardWrite) (r *DashboardPublicHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDataset implements createDataset operation.
//
// Create dataset.
//
// POST /v1/private/datasets
func (UnimplementedHandler) CreateDataset(ctx context.Context, req OptDatasetWrite) (r *CreateDatasetCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDatasetItemsFromCsv implements createDatasetItemsFromCsv operation.
//
// Create dataset items from uploaded CSV file. CSV should have headers in the first row. Processing
// happens asynchronously in batches.
//
// POST /v1/private/datasets/items/from-csv
func (UnimplementedHandler) CreateDatasetItemsFromCsv(ctx context.Context, req OptCreateDatasetItemsFromCsvReq) (r CreateDatasetItemsFromCsvRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDatasetItemsFromSpans implements createDatasetItemsFromSpans operation.
//
// Create dataset items from spans with enriched metadata.
//
// POST /v1/private/datasets/{dataset_id}/items/from-spans
func (UnimplementedHandler) CreateDatasetItemsFromSpans(ctx context.Context, req OptCreateDatasetItemsFromSpansRequest, params CreateDatasetItemsFromSpansParams) error {
	return ht.ErrNotImplemented
}

// CreateDatasetItemsFromTraces implements createDatasetItemsFromTraces operation.
//
// Create dataset items from traces with enriched metadata.
//
// POST /v1/private/datasets/{dataset_id}/items/from-traces
func (UnimplementedHandler) CreateDatasetItemsFromTraces(ctx context.Context, req OptCreateDatasetItemsFromTracesRequest, params CreateDatasetItemsFromTracesParams) error {
	return ht.ErrNotImplemented
}

// CreateDatasetVersion implements createDatasetVersion operation.
//
// Create a new immutable version of the dataset by snapshotting the current state.
//
// POST /v1/private/datasets/{id}/versions
func (UnimplementedHandler) CreateDatasetVersion(ctx context.Context, req OptDatasetVersionCreatePublic, params CreateDatasetVersionParams) (r CreateDatasetVersionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateExperiment implements createExperiment operation.
//
// Create experiment.
//
// POST /v1/private/experiments
func (UnimplementedHandler) CreateExperiment(ctx context.Context, req OptExperimentWrite) (r *CreateExperimentCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateExperimentItems implements createExperimentItems operation.
//
// Create experiment items.
//
// POST /v1/private/experiments/items
func (UnimplementedHandler) CreateExperimentItems(ctx context.Context, req OptExperimentItemsBatch) error {
	return ht.ErrNotImplemented
}

// CreateFeedbackDefinition implements createFeedbackDefinition operation.
//
// Get feedback definition.
//
// POST /v1/private/feedback-definitions
func (UnimplementedHandler) CreateFeedbackDefinition(ctx context.Context, req OptFeedbackCreate) (r *CreateFeedbackDefinitionCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateGuardrails implements createGuardrails operation.
//
// Batch guardrails for traces.
//
// POST /v1/private/guardrails
func (UnimplementedHandler) CreateGuardrails(ctx context.Context, req OptGuardrailBatchWrite) error {
	return ht.ErrNotImplemented
}

// CreateOptimization implements createOptimization operation.
//
// Create optimization.
//
// POST /v1/private/optimizations
func (UnimplementedHandler) CreateOptimization(ctx context.Context, req OptOptimizationWrite) (r *CreateOptimizationCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrUpdateDatasetItems implements createOrUpdateDatasetItems operation.
//
// Create/update dataset items based on dataset item id.
//
// PUT /v1/private/datasets/items
func (UnimplementedHandler) CreateOrUpdateDatasetItems(ctx context.Context, req OptDatasetItemBatchWrite) error {
	return ht.ErrNotImplemented
}

// CreateProject implements createProject operation.
//
// Create project.
//
// POST /v1/private/projects
func (UnimplementedHandler) CreateProject(ctx context.Context, req OptProjectWrite) (r CreateProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePrompt implements createPrompt operation.
//
// Create prompt.
//
// POST /v1/private/prompts
func (UnimplementedHandler) CreatePrompt(ctx context.Context, req OptPromptWrite) (r CreatePromptRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePromptVersion implements createPromptVersion operation.
//
// Create prompt version.
//
// POST /v1/private/prompts/versions
func (UnimplementedHandler) CreatePromptVersion(ctx context.Context, req OptCreatePromptVersionDetail) (r CreatePromptVersionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSpan implements createSpan operation.
//
// Create span.
//
// POST /v1/private/spans
func (UnimplementedHandler) CreateSpan(ctx context.Context, req OptSpanWrite) (r CreateSpanRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSpans implements createSpans operation.
//
// Create spans.
//
// POST /v1/private/spans/batch
func (UnimplementedHandler) CreateSpans(ctx context.Context, req OptSpanBatchWrite) error {
	return ht.ErrNotImplemented
}

// CreateTrace implements createTrace operation.
//
// Get trace.
//
// POST /v1/private/traces
func (UnimplementedHandler) CreateTrace(ctx context.Context, req OptTraceWrite) (r *CreateTraceCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTraces implements createTraces operation.
//
// Create traces.
//
// POST /v1/private/traces/batch
func (UnimplementedHandler) CreateTraces(ctx context.Context, req OptTraceBatchWrite) error {
	return ht.ErrNotImplemented
}

// CreateVersionTag implements createVersionTag operation.
//
// Add a tag to a specific dataset version for easy reference (e.g., 'baseline', 'v1.0', 'production').
//
// POST /v1/private/datasets/{id}/versions/hash/{versionHash}/tags
func (UnimplementedHandler) CreateVersionTag(ctx context.Context, req OptDatasetVersionTag, params CreateVersionTagParams) (r CreateVersionTagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAlertBatch implements deleteAlertBatch operation.
//
// Delete multiple alerts by their IDs.
//
// POST /v1/private/alerts/delete
func (UnimplementedHandler) DeleteAlertBatch(ctx context.Context, req OptBatchDelete) (r DeleteAlertBatchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAnnotationQueueBatch implements deleteAnnotationQueueBatch operation.
//
// Delete multiple annotation queues by their IDs.
//
// POST /v1/private/annotation-queues/delete
func (UnimplementedHandler) DeleteAnnotationQueueBatch(ctx context.Context, req OptBatchDelete) (r DeleteAnnotationQueueBatchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAttachments implements deleteAttachments operation.
//
// Delete attachments.
//
// POST /v1/private/attachment/delete
func (UnimplementedHandler) DeleteAttachments(ctx context.Context, req OptCompleteMultipartUploadRequest) (r DeleteAttachmentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAutomationRuleEvaluatorBatch implements deleteAutomationRuleEvaluatorBatch operation.
//
// Delete automation rule evaluators batch.
//
// POST /v1/private/automations/evaluators/delete
func (UnimplementedHandler) DeleteAutomationRuleEvaluatorBatch(ctx context.Context, req OptBatchDelete, params DeleteAutomationRuleEvaluatorBatchParams) error {
	return ht.ErrNotImplemented
}

// DeleteDashboard implements deleteDashboard operation.
//
// Delete dashboard by id.
//
// DELETE /v1/private/dashboards/{dashboardId}
func (UnimplementedHandler) DeleteDashboard(ctx context.Context, params DeleteDashboardParams) error {
	return ht.ErrNotImplemented
}

// DeleteDashboardsBatch implements deleteDashboardsBatch operation.
//
// Delete dashboards batch.
//
// POST /v1/private/dashboards/delete-batch
func (UnimplementedHandler) DeleteDashboardsBatch(ctx context.Context, req OptBatchDelete) error {
	return ht.ErrNotImplemented
}

// DeleteDataset implements deleteDataset operation.
//
// Delete dataset by id.
//
// DELETE /v1/private/datasets/{id}
func (UnimplementedHandler) DeleteDataset(ctx context.Context, params DeleteDatasetParams) error {
	return ht.ErrNotImplemented
}

// DeleteDatasetByName implements deleteDatasetByName operation.
//
// Delete dataset by name.
//
// POST /v1/private/datasets/delete
func (UnimplementedHandler) DeleteDatasetByName(ctx context.Context, req OptDatasetIdentifier) error {
	return ht.ErrNotImplemented
}

// DeleteDatasetItems implements deleteDatasetItems operation.
//
// Delete dataset items using one of two modes:
// 1. **Delete by IDs**: Provide 'item_ids' to delete specific items by their IDs
// 2. **Delete by filters**: Provide 'dataset_id' with optional 'filters' to delete items matching
// criteria
// When using filters, an empty 'filters' array will delete all items in the specified dataset.
//
// POST /v1/private/datasets/items/delete
func (UnimplementedHandler) DeleteDatasetItems(ctx context.Context, req OptDatasetItemsDelete) (r DeleteDatasetItemsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDatasetsBatch implements deleteDatasetsBatch operation.
//
// Delete datasets batch.
//
// POST /v1/private/datasets/delete-batch
func (UnimplementedHandler) DeleteDatasetsBatch(ctx context.Context, req OptBatchDelete) error {
	return ht.ErrNotImplemented
}

// DeleteExperimentItems implements deleteExperimentItems operation.
//
// Delete experiment items.
//
// POST /v1/private/experiments/items/delete
func (UnimplementedHandler) DeleteExperimentItems(ctx context.Context, req OptExperimentItemsDelete) error {
	return ht.ErrNotImplemented
}

// DeleteExperimentsById implements deleteExperimentsById operation.
//
// Delete experiments by id.
//
// POST /v1/private/experiments/delete
func (UnimplementedHandler) DeleteExperimentsById(ctx context.Context, req OptDeleteIdsHolder) error {
	return ht.ErrNotImplemented
}

// DeleteFeedbackDefinitionById implements deleteFeedbackDefinitionById operation.
//
// Delete feedback definition by id.
//
// DELETE /v1/private/feedback-definitions/{id}
func (UnimplementedHandler) DeleteFeedbackDefinitionById(ctx context.Context, params DeleteFeedbackDefinitionByIdParams) (r DeleteFeedbackDefinitionByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteFeedbackDefinitionsBatch implements deleteFeedbackDefinitionsBatch operation.
//
// Delete feedback definitions batch.
//
// POST /v1/private/feedback-definitions/delete
func (UnimplementedHandler) DeleteFeedbackDefinitionsBatch(ctx context.Context, req OptBatchDelete) (r DeleteFeedbackDefinitionsBatchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteLlmProviderApiKeysBatch implements deleteLlmProviderApiKeysBatch operation.
//
// Delete LLM Provider's ApiKeys batch.
//
// POST /v1/private/llm-provider-key/delete
func (UnimplementedHandler) DeleteLlmProviderApiKeysBatch(ctx context.Context, req OptBatchDelete) error {
	return ht.ErrNotImplemented
}

// DeleteOptimizationsById implements deleteOptimizationsById operation.
//
// Delete optimizations by id.
//
// POST /v1/private/optimizations/delete
func (UnimplementedHandler) DeleteOptimizationsById(ctx context.Context, req OptDeleteIdsHolder) error {
	return ht.ErrNotImplemented
}

// DeleteProjectById implements deleteProjectById operation.
//
// Delete project by id.
//
// DELETE /v1/private/projects/{id}
func (UnimplementedHandler) DeleteProjectById(ctx context.Context, params DeleteProjectByIdParams) (r DeleteProjectByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteProjectsBatch implements deleteProjectsBatch operation.
//
// Delete projects batch.
//
// POST /v1/private/projects/delete
func (UnimplementedHandler) DeleteProjectsBatch(ctx context.Context, req OptBatchDelete) error {
	return ht.ErrNotImplemented
}

// DeletePrompt implements deletePrompt operation.
//
// Delete prompt.
//
// DELETE /v1/private/prompts/{id}
func (UnimplementedHandler) DeletePrompt(ctx context.Context, params DeletePromptParams) error {
	return ht.ErrNotImplemented
}

// DeletePromptsBatch implements deletePromptsBatch operation.
//
// Delete prompts batch.
//
// POST /v1/private/prompts/delete
func (UnimplementedHandler) DeletePromptsBatch(ctx context.Context, req OptBatchDelete) error {
	return ht.ErrNotImplemented
}

// DeleteSpanById implements deleteSpanById operation.
//
// Delete span by id.
//
// DELETE /v1/private/spans/{id}
func (UnimplementedHandler) DeleteSpanById(ctx context.Context, params DeleteSpanByIdParams) (r DeleteSpanByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSpanComments implements deleteSpanComments operation.
//
// Delete span comments.
//
// POST /v1/private/spans/comments/delete
func (UnimplementedHandler) DeleteSpanComments(ctx context.Context, req OptBatchDelete) error {
	return ht.ErrNotImplemented
}

// DeleteSpanFeedbackScore implements deleteSpanFeedbackScore operation.
//
// Delete span feedback score.
//
// POST /v1/private/spans/{id}/feedback-scores/delete
func (UnimplementedHandler) DeleteSpanFeedbackScore(ctx context.Context, req OptDeleteFeedbackScore, params DeleteSpanFeedbackScoreParams) error {
	return ht.ErrNotImplemented
}

// DeleteThreadComments implements deleteThreadComments operation.
//
// Delete thread comments.
//
// POST /v1/private/traces/threads/comments/delete
func (UnimplementedHandler) DeleteThreadComments(ctx context.Context, req OptBatchDelete) error {
	return ht.ErrNotImplemented
}

// DeleteThreadFeedbackScores implements deleteThreadFeedbackScores operation.
//
// Delete thread feedback scores.
//
// POST /v1/private/traces/threads/feedback-scores/delete
func (UnimplementedHandler) DeleteThreadFeedbackScores(ctx context.Context, req OptDeleteThreadFeedbackScores) error {
	return ht.ErrNotImplemented
}

// DeleteTraceById implements deleteTraceById operation.
//
// Delete trace by id.
//
// DELETE /v1/private/traces/{id}
func (UnimplementedHandler) DeleteTraceById(ctx context.Context, params DeleteTraceByIdParams) error {
	return ht.ErrNotImplemented
}

// DeleteTraceComments implements deleteTraceComments operation.
//
// Delete trace comments.
//
// POST /v1/private/traces/comments/delete
func (UnimplementedHandler) DeleteTraceComments(ctx context.Context, req OptBatchDelete) error {
	return ht.ErrNotImplemented
}

// DeleteTraceFeedbackScore implements deleteTraceFeedbackScore operation.
//
// Delete trace feedback score.
//
// POST /v1/private/traces/{id}/feedback-scores/delete
func (UnimplementedHandler) DeleteTraceFeedbackScore(ctx context.Context, req OptDeleteFeedbackScore, params DeleteTraceFeedbackScoreParams) error {
	return ht.ErrNotImplemented
}

// DeleteTraceThreads implements deleteTraceThreads operation.
//
// Delete trace threads.
//
// POST /v1/private/traces/threads/delete
func (UnimplementedHandler) DeleteTraceThreads(ctx context.Context, req OptDeleteTraceThreads) error {
	return ht.ErrNotImplemented
}

// DeleteTraces implements deleteTraces operation.
//
// Delete traces.
//
// POST /v1/private/traces/delete
func (UnimplementedHandler) DeleteTraces(ctx context.Context, req OptBatchDelete) error {
	return ht.ErrNotImplemented
}

// DeleteVersionTag implements deleteVersionTag operation.
//
// Remove a tag from a dataset version. The version itself is not deleted, only the tag reference.
//
// DELETE /v1/private/datasets/{id}/versions/{versionHash}/tags/{tag}
func (UnimplementedHandler) DeleteVersionTag(ctx context.Context, params DeleteVersionTagParams) error {
	return ht.ErrNotImplemented
}

// DeleteWorkspaceConfiguration implements deleteWorkspaceConfiguration operation.
//
// Delete workspace configuration.
//
// DELETE /v1/private/workspaces/configurations
func (UnimplementedHandler) DeleteWorkspaceConfiguration(ctx context.Context) (r DeleteWorkspaceConfigurationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EvaluateSpans implements evaluateSpans operation.
//
// Manually trigger evaluation rules on selected spans. Bypasses sampling and enqueues all specified
// spans for evaluation.
//
// POST /v1/private/manual-evaluation/spans
func (UnimplementedHandler) EvaluateSpans(ctx context.Context, req OptManualEvaluationRequest) (r EvaluateSpansRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EvaluateThreads implements evaluateThreads operation.
//
// Manually trigger evaluation rules on selected threads. Bypasses sampling and enqueues all
// specified threads for evaluation.
//
// POST /v1/private/manual-evaluation/threads
func (UnimplementedHandler) EvaluateThreads(ctx context.Context, req OptManualEvaluationRequest) (r EvaluateThreadsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EvaluateTraces implements evaluateTraces operation.
//
// Manually trigger evaluation rules on selected traces. Bypasses sampling and enqueues all specified
// traces for evaluation.
//
// POST /v1/private/manual-evaluation/traces
func (UnimplementedHandler) EvaluateTraces(ctx context.Context, req OptManualEvaluationRequest) (r EvaluateTracesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ExpandDataset implements expandDataset operation.
//
// Generate synthetic dataset samples using LLM based on existing data patterns.
//
// POST /v1/private/datasets/{id}/expansions
func (UnimplementedHandler) ExpandDataset(ctx context.Context, req OptDatasetExpansionWrite, params ExpandDatasetParams) (r *DatasetExpansionResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ExperimentItemsBulk implements experimentItemsBulk operation.
//
// Record experiment items in bulk with traces, spans, and feedback scores. Maximum request size is
// 4MB.
//
// PUT /v1/private/experiments/items/bulk
func (UnimplementedHandler) ExperimentItemsBulk(ctx context.Context, req OptExperimentItemBulkUploadExperimentItemBulkWriteView) (r ExperimentItemsBulkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FindAlerts implements findAlerts operation.
//
// Find alerts.
//
// GET /v1/private/alerts
func (UnimplementedHandler) FindAlerts(ctx context.Context, params FindAlertsParams) (r *AlertPagePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// FindAnnotationQueues implements findAnnotationQueues operation.
//
// Find annotation queues with filtering and sorting.
//
// GET /v1/private/annotation-queues
func (UnimplementedHandler) FindAnnotationQueues(ctx context.Context, params FindAnnotationQueuesParams) (r *AnnotationQueuePagePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// FindDashboards implements findDashboards operation.
//
// Find dashboards in a workspace.
//
// GET /v1/private/dashboards
func (UnimplementedHandler) FindDashboards(ctx context.Context, params FindDashboardsParams) (r *DashboardPagePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// FindDatasetItemsWithExperimentItems implements findDatasetItemsWithExperimentItems operation.
//
// Find dataset items with experiment items.
//
// GET /v1/private/datasets/{id}/items/experiments/items
func (UnimplementedHandler) FindDatasetItemsWithExperimentItems(ctx context.Context, params FindDatasetItemsWithExperimentItemsParams) (r *DatasetItemPageCompare, _ error) {
	return r, ht.ErrNotImplemented
}

// FindDatasets implements findDatasets operation.
//
// Find datasets.
//
// GET /v1/private/datasets
func (UnimplementedHandler) FindDatasets(ctx context.Context, params FindDatasetsParams) (r *DatasetPagePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// FindEvaluators implements findEvaluators operation.
//
// Find project Evaluators.
//
// GET /v1/private/automations/evaluators
func (UnimplementedHandler) FindEvaluators(ctx context.Context, params FindEvaluatorsParams) (r *AutomationRuleEvaluatorPagePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// FindExperimentGroups implements findExperimentGroups operation.
//
// Find experiments grouped by specified fields.
//
// GET /v1/private/experiments/groups
func (UnimplementedHandler) FindExperimentGroups(ctx context.Context, params FindExperimentGroupsParams) (r FindExperimentGroupsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FindExperimentGroupsAggregations implements findExperimentGroupsAggregations operation.
//
// Find experiments grouped by specified fields with aggregation metrics.
//
// GET /v1/private/experiments/groups/aggregations
func (UnimplementedHandler) FindExperimentGroupsAggregations(ctx context.Context, params FindExperimentGroupsAggregationsParams) (r FindExperimentGroupsAggregationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FindExperiments implements findExperiments operation.
//
// Find experiments.
//
// GET /v1/private/experiments
func (UnimplementedHandler) FindExperiments(ctx context.Context, params FindExperimentsParams) (r FindExperimentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FindFeedbackDefinitions implements findFeedbackDefinitions operation.
//
// Find Feedback definitions.
//
// GET /v1/private/feedback-definitions
func (UnimplementedHandler) FindFeedbackDefinitions(ctx context.Context, params FindFeedbackDefinitionsParams) (r *FeedbackDefinitionPagePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// FindFeedbackScoreNames implements findFeedbackScoreNames operation.
//
// Find Feedback Score names.
//
// GET /v1/private/experiments/feedback-scores/names
func (UnimplementedHandler) FindFeedbackScoreNames(ctx context.Context, params FindFeedbackScoreNamesParams) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}

// FindFeedbackScoreNames1 implements findFeedbackScoreNames_1 operation.
//
// Find Feedback Score names.
//
// GET /v1/private/spans/feedback-scores/names
func (UnimplementedHandler) FindFeedbackScoreNames1(ctx context.Context, params FindFeedbackScoreNames1Params) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}

// FindFeedbackScoreNames2 implements findFeedbackScoreNames_2 operation.
//
// Find Feedback Score names.
//
// GET /v1/private/traces/feedback-scores/names
func (UnimplementedHandler) FindFeedbackScoreNames2(ctx context.Context, params FindFeedbackScoreNames2Params) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}

// FindFeedbackScoreNamesByProjectIds implements findFeedbackScoreNamesByProjectIds operation.
//
// Find Feedback Score names By Project Ids.
//
// GET /v1/private/projects/feedback-scores/names
func (UnimplementedHandler) FindFeedbackScoreNamesByProjectIds(ctx context.Context, params FindFeedbackScoreNamesByProjectIdsParams) (r *FeedbackScoreNames, _ error) {
	return r, ht.ErrNotImplemented
}

// FindLlmProviderKeys implements findLlmProviderKeys operation.
//
// Find LLM Provider's ApiKeys.
//
// GET /v1/private/llm-provider-key
func (UnimplementedHandler) FindLlmProviderKeys(ctx context.Context) (r *ProviderApiKeyPagePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// FindOptimizations implements findOptimizations operation.
//
// Find optimizations.
//
// GET /v1/private/optimizations
func (UnimplementedHandler) FindOptimizations(ctx context.Context, params FindOptimizationsParams) (r FindOptimizationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FindProjects implements findProjects operation.
//
// Find projects.
//
// GET /v1/private/projects
func (UnimplementedHandler) FindProjects(ctx context.Context, params FindProjectsParams) (r *ProjectPagePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// FindStudioOptimizations implements findStudioOptimizations operation.
//
// Find Studio optimizations.
//
// GET /v1/private/optimizations/studio
func (UnimplementedHandler) FindStudioOptimizations(ctx context.Context, params FindStudioOptimizationsParams) (r FindStudioOptimizationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FindTraceThreadsFeedbackScoreNames implements findTraceThreadsFeedbackScoreNames operation.
//
// Find Trace Threads Feedback Score names.
//
// GET /v1/private/traces/threads/feedback-scores/names
func (UnimplementedHandler) FindTraceThreadsFeedbackScoreNames(ctx context.Context, params FindTraceThreadsFeedbackScoreNamesParams) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}

// FinishExperiments implements finishExperiments operation.
//
// Finish experiments and trigger alert events.
//
// POST /v1/private/experiments/finish
func (UnimplementedHandler) FinishExperiments(ctx context.Context, req OptDeleteIdsHolder) (r FinishExperimentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAlertById implements getAlertById operation.
//
// Get Alert by id.
//
// GET /v1/private/alerts/{id}
func (UnimplementedHandler) GetAlertById(ctx context.Context, params GetAlertByIdParams) (r GetAlertByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAnnotationQueueById implements getAnnotationQueueById operation.
//
// Get annotation queue by id.
//
// GET /v1/private/annotation-queues/{id}
func (UnimplementedHandler) GetAnnotationQueueById(ctx context.Context, params GetAnnotationQueueByIdParams) (r GetAnnotationQueueByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCost implements getCost operation.
//
// Get cost daily data.
//
// POST /v1/private/workspaces/costs
func (UnimplementedHandler) GetCost(ctx context.Context, req OptWorkspaceMetricsSummaryRequest) (r GetCostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDashboardById implements getDashboardById operation.
//
// Get dashboard by id.
//
// GET /v1/private/dashboards/{dashboardId}
func (UnimplementedHandler) GetDashboardById(ctx context.Context, params GetDashboardByIdParams) (r GetDashboardByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDatasetBiInfo implements getDatasetBiInfo operation.
//
// Get datasets information for BI events per user per workspace.
//
// GET /v1/internal/usage/bi-datasets
func (UnimplementedHandler) GetDatasetBiInfo(ctx context.Context) (r *BiInformationResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDatasetById implements getDatasetById operation.
//
// Get dataset by id.
//
// GET /v1/private/datasets/{id}
func (UnimplementedHandler) GetDatasetById(ctx context.Context, params GetDatasetByIdParams) (r *DatasetPublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDatasetByIdentifier implements getDatasetByIdentifier operation.
//
// Get dataset by name.
//
// POST /v1/private/datasets/retrieve
func (UnimplementedHandler) GetDatasetByIdentifier(ctx context.Context, req OptDatasetIdentifierPublic) (r *DatasetPublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDatasetExperimentItemsStats implements getDatasetExperimentItemsStats operation.
//
// Get experiment items stats for dataset.
//
// GET /v1/private/datasets/{id}/items/experiments/items/stats
func (UnimplementedHandler) GetDatasetExperimentItemsStats(ctx context.Context, params GetDatasetExperimentItemsStatsParams) (r *ProjectStatsPublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDatasetItemById implements getDatasetItemById operation.
//
// Get dataset item by id.
//
// GET /v1/private/datasets/items/{itemId}
func (UnimplementedHandler) GetDatasetItemById(ctx context.Context, params GetDatasetItemByIdParams) (r *DatasetItemPublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDatasetItems implements getDatasetItems operation.
//
// Get dataset items.
//
// GET /v1/private/datasets/{id}/items
func (UnimplementedHandler) GetDatasetItems(ctx context.Context, params GetDatasetItemsParams) (r *DatasetItemPagePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDatasetItemsOutputColumns implements getDatasetItemsOutputColumns operation.
//
// Get dataset items output columns.
//
// GET /v1/private/datasets/{id}/items/experiments/items/output/columns
func (UnimplementedHandler) GetDatasetItemsOutputColumns(ctx context.Context, params GetDatasetItemsOutputColumnsParams) (r *PageColumns, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEvaluatorById implements getEvaluatorById operation.
//
// Get automation rule by id.
//
// GET /v1/private/automations/evaluators/{id}
func (UnimplementedHandler) GetEvaluatorById(ctx context.Context, params GetEvaluatorByIdParams) (r *AutomationRuleEvaluatorPublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEvaluatorLogsById implements getEvaluatorLogsById operation.
//
// Get automation rule evaluator logs by id.
//
// GET /v1/private/automations/evaluators/{id}/logs
func (UnimplementedHandler) GetEvaluatorLogsById(ctx context.Context, params GetEvaluatorLogsByIdParams) (r *LogPage, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExperimentBiInfo implements getExperimentBiInfo operation.
//
// Get experiments information for BI events per user per workspace.
//
// GET /v1/internal/usage/bi-experiments
func (UnimplementedHandler) GetExperimentBiInfo(ctx context.Context) (r *BiInformationResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExperimentById implements getExperimentById operation.
//
// Get experiment by id.
//
// GET /v1/private/experiments/{id}
func (UnimplementedHandler) GetExperimentById(ctx context.Context, params GetExperimentByIdParams) (r GetExperimentByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExperimentItemById implements getExperimentItemById operation.
//
// Get experiment item by id.
//
// GET /v1/private/experiments/items/{id}
func (UnimplementedHandler) GetExperimentItemById(ctx context.Context, params GetExperimentItemByIdParams) (r GetExperimentItemByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFeedbackDefinitionById implements getFeedbackDefinitionById operation.
//
// Get feedback definition by id.
//
// GET /v1/private/feedback-definitions/{id}
func (UnimplementedHandler) GetFeedbackDefinitionById(ctx context.Context, params GetFeedbackDefinitionByIdParams) (r *FeedbackPublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLlmProviderApiKeyById implements getLlmProviderApiKeyById operation.
//
// Get LLM Provider's ApiKey by id.
//
// GET /v1/private/llm-provider-key/{id}
func (UnimplementedHandler) GetLlmProviderApiKeyById(ctx context.Context, params GetLlmProviderApiKeyByIdParams) (r GetLlmProviderApiKeyByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMetric implements getMetric operation.
//
// Get metric daily data.
//
// Deprecated: schema marks this operation as deprecated.
//
// POST /v1/private/workspaces/metrics
func (UnimplementedHandler) GetMetric(ctx context.Context, req OptWorkspaceMetricsSummaryRequest) (r GetMetricRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOptimizationById implements getOptimizationById operation.
//
// Get optimization by id.
//
// GET /v1/private/optimizations/{id}
func (UnimplementedHandler) GetOptimizationById(ctx context.Context, params GetOptimizationByIdParams) (r GetOptimizationByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjectById implements getProjectById operation.
//
// Get project by id.
//
// GET /v1/private/projects/{id}
func (UnimplementedHandler) GetProjectById(ctx context.Context, params GetProjectByIdParams) (r *ProjectPublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjectMetrics implements getProjectMetrics operation.
//
// Gets specified metrics for a project.
//
// POST /v1/private/projects/{id}/metrics
func (UnimplementedHandler) GetProjectMetrics(ctx context.Context, req OptProjectMetricRequestPublic, params GetProjectMetricsParams) (r GetProjectMetricsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjectStats implements getProjectStats operation.
//
// Get Project Stats.
//
// GET /v1/private/projects/stats
func (UnimplementedHandler) GetProjectStats(ctx context.Context, params GetProjectStatsParams) (r *ProjectStatsSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPromptById implements getPromptById operation.
//
// Get prompt by id.
//
// GET /v1/private/prompts/{id}
func (UnimplementedHandler) GetPromptById(ctx context.Context, params GetPromptByIdParams) (r GetPromptByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPromptVersionById implements getPromptVersionById operation.
//
// Get prompt version by id.
//
// GET /v1/private/prompts/versions/{versionId}
func (UnimplementedHandler) GetPromptVersionById(ctx context.Context, params GetPromptVersionByIdParams) (r GetPromptVersionByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPromptVersions implements getPromptVersions operation.
//
// Get prompt versions.
//
// GET /v1/private/prompts/{id}/versions
func (UnimplementedHandler) GetPromptVersions(ctx context.Context, params GetPromptVersionsParams) (r *PromptVersionPagePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPrompts implements getPrompts operation.
//
// Get prompts.
//
// GET /v1/private/prompts
func (UnimplementedHandler) GetPrompts(ctx context.Context, params GetPromptsParams) (r *PromptPagePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServiceToggles implements getServiceToggles operation.
//
// Get Service Toggles.
//
// GET /v1/private/toggles
func (UnimplementedHandler) GetServiceToggles(ctx context.Context) (r *ServiceTogglesConfig, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpanById implements getSpanById operation.
//
// Get span by id.
//
// GET /v1/private/spans/{id}
func (UnimplementedHandler) GetSpanById(ctx context.Context, params GetSpanByIdParams) (r GetSpanByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpanComment implements getSpanComment operation.
//
// Get span comment.
//
// GET /v1/private/spans/{spanId}/comments/{commentId}
func (UnimplementedHandler) GetSpanComment(ctx context.Context, params GetSpanCommentParams) (r GetSpanCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpanStats implements getSpanStats operation.
//
// Get span stats.
//
// GET /v1/private/spans/stats
func (UnimplementedHandler) GetSpanStats(ctx context.Context, params GetSpanStatsParams) (r *ProjectStatsPublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpansBiInfo implements getSpansBiInfo operation.
//
// Get spans information for BI events per user per workspace.
//
// GET /v1/internal/usage/bi-spans
func (UnimplementedHandler) GetSpansBiInfo(ctx context.Context) (r *BiInformationResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpansByProject implements getSpansByProject operation.
//
// Get spans by project_name or project_id and optionally by trace_id and/or type.
//
// GET /v1/private/spans
func (UnimplementedHandler) GetSpansByProject(ctx context.Context, params GetSpansByProjectParams) (r *SpanPagePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpansCountForWorkspaces implements getSpansCountForWorkspaces operation.
//
// Get spans count on previous day for all available workspaces.
//
// GET /v1/internal/usage/workspace-span-counts
func (UnimplementedHandler) GetSpansCountForWorkspaces(ctx context.Context) (r *SpansCountResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStudioOptimizationById implements getStudioOptimizationById operation.
//
// Get Studio optimization with config included.
//
// GET /v1/private/optimizations/studio/{id}
func (UnimplementedHandler) GetStudioOptimizationById(ctx context.Context, params GetStudioOptimizationByIdParams) (r GetStudioOptimizationByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStudioOptimizationLogs implements getStudioOptimizationLogs operation.
//
// Get presigned S3 URL for downloading optimization logs.
//
// GET /v1/private/optimizations/studio/{id}/logs
func (UnimplementedHandler) GetStudioOptimizationLogs(ctx context.Context, params GetStudioOptimizationLogsParams) (r GetStudioOptimizationLogsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetThreadComment implements getThreadComment operation.
//
// Get thread comment.
//
// GET /v1/private/traces/threads/{threadId}/comments/{commentId}
func (UnimplementedHandler) GetThreadComment(ctx context.Context, params GetThreadCommentParams) (r GetThreadCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTraceById implements getTraceById operation.
//
// Get trace by id.
//
// GET /v1/private/traces/{id}
func (UnimplementedHandler) GetTraceById(ctx context.Context, params GetTraceByIdParams) (r *TracePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTraceComment implements getTraceComment operation.
//
// Get trace comment.
//
// GET /v1/private/traces/{traceId}/comments/{commentId}
func (UnimplementedHandler) GetTraceComment(ctx context.Context, params GetTraceCommentParams) (r GetTraceCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTraceStats implements getTraceStats operation.
//
// Get trace stats.
//
// GET /v1/private/traces/stats
func (UnimplementedHandler) GetTraceStats(ctx context.Context, params GetTraceStatsParams) (r *ProjectStatsPublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTraceThread implements getTraceThread operation.
//
// Get trace thread.
//
// POST /v1/private/traces/threads/retrieve
func (UnimplementedHandler) GetTraceThread(ctx context.Context, req OptTraceThreadIdentifier) (r GetTraceThreadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTraceThreadStats implements getTraceThreadStats operation.
//
// Get trace thread stats.
//
// GET /v1/private/traces/threads/stats
func (UnimplementedHandler) GetTraceThreadStats(ctx context.Context, params GetTraceThreadStatsParams) (r *ProjectStatsPublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTraceThreads implements getTraceThreads operation.
//
// Get trace threads.
//
// GET /v1/private/traces/threads
func (UnimplementedHandler) GetTraceThreads(ctx context.Context, params GetTraceThreadsParams) (r *TraceThreadPage, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTracesBiInfo implements getTracesBiInfo operation.
//
// Get traces information for BI events per user per workspace.
//
// GET /v1/internal/usage/bi-traces
func (UnimplementedHandler) GetTracesBiInfo(ctx context.Context) (r *BiInformationResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTracesByProject implements getTracesByProject operation.
//
// Get traces by project_name or project_id.
//
// GET /v1/private/traces
func (UnimplementedHandler) GetTracesByProject(ctx context.Context, params GetTracesByProjectParams) (r *TracePagePublic, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTracesCountForWorkspaces implements getTracesCountForWorkspaces operation.
//
// Get traces count on previous day for all available workspaces.
//
// GET /v1/internal/usage/workspace-trace-counts
func (UnimplementedHandler) GetTracesCountForWorkspaces(ctx context.Context) (r *TraceCountResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWebhookExamples implements getWebhookExamples operation.
//
// Get webhook payload examples for all alert event types, optionally filtered by alert type.
//
// GET /v1/private/alerts/webhooks/examples
func (UnimplementedHandler) GetWebhookExamples(ctx context.Context, params GetWebhookExamplesParams) (r *WebhookExamples, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWelcomeWizardStatus implements getWelcomeWizardStatus operation.
//
// Get welcome wizard tracking status for the current workspace.
//
// GET /v1/private/welcome-wizard
func (UnimplementedHandler) GetWelcomeWizardStatus(ctx context.Context) (r *WelcomeWizardTracking, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspaceConfiguration implements getWorkspaceConfiguration operation.
//
// Get workspace configuration.
//
// GET /v1/private/workspaces/configurations
func (UnimplementedHandler) GetWorkspaceConfiguration(ctx context.Context) (r GetWorkspaceConfigurationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspaceName implements getWorkspaceName operation.
//
// User's default workspace name.
//
// GET /v1/private/auth/workspace
func (UnimplementedHandler) GetWorkspaceName(ctx context.Context) (r GetWorkspaceNameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// IsAlive implements isAlive operation.
//
// GET /is-alive/ping
func (UnimplementedHandler) IsAlive(ctx context.Context) (r *IsAliveDefStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDatasetVersions implements listDatasetVersions operation.
//
// Get paginated list of versions for a dataset, ordered by creation time (newest first).
//
// GET /v1/private/datasets/{id}/versions
func (UnimplementedHandler) ListDatasetVersions(ctx context.Context, params ListDatasetVersionsParams) (r ListDatasetVersionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MetricsSummary implements metricsSummary operation.
//
// Get metrics summary.
//
// Deprecated: schema marks this operation as deprecated.
//
// POST /v1/private/workspaces/metrics/summaries
func (UnimplementedHandler) MetricsSummary(ctx context.Context, req OptWorkspaceMetricsSummaryRequest) (r MetricsSummaryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OpenTraceThread implements openTraceThread operation.
//
// Open trace thread.
//
// PUT /v1/private/traces/threads/open
func (UnimplementedHandler) OpenTraceThread(ctx context.Context, req OptTraceThreadIdentifier) error {
	return ht.ErrNotImplemented
}

// PatchDatasetItem implements patchDatasetItem operation.
//
// Partially update dataset item by id. Only provided fields will be updated.
//
// PATCH /v1/private/datasets/items/{itemId}
func (UnimplementedHandler) PatchDatasetItem(ctx context.Context, req OptDatasetItemWrite, params PatchDatasetItemParams) (r PatchDatasetItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveItemsFromAnnotationQueue implements removeItemsFromAnnotationQueue operation.
//
// Remove items from annotation queue.
//
// POST /v1/private/annotation-queues/{id}/items/delete
func (UnimplementedHandler) RemoveItemsFromAnnotationQueue(ctx context.Context, req OptAnnotationQueueItemIds, params RemoveItemsFromAnnotationQueueParams) (r RemoveItemsFromAnnotationQueueRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RestoreDatasetVersion implements restoreDatasetVersion operation.
//
// Restores the dataset to a previous version state. All draft items are replaced with items from the
// specified version. If the version is not the latest, a new version snapshot is created. If the
// version is the latest, only draft items are replaced (revert functionality).
//
// POST /v1/private/datasets/{id}/versions/restore
func (UnimplementedHandler) RestoreDatasetVersion(ctx context.Context, req OptDatasetVersionRestorePublic, params RestoreDatasetVersionParams) (r RestoreDatasetVersionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RestorePromptVersion implements restorePromptVersion operation.
//
// Restore a prompt version by creating a new version with the content from the specified version.
//
// POST /v1/private/prompts/{promptId}/versions/{versionId}/restore
func (UnimplementedHandler) RestorePromptVersion(ctx context.Context, params RestorePromptVersionParams) (r RestorePromptVersionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RetrieveProject implements retrieveProject operation.
//
// Retrieve project.
//
// POST /v1/private/projects/retrieve
func (UnimplementedHandler) RetrieveProject(ctx context.Context, req OptProjectRetrieveDetailed) (r RetrieveProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RetrievePromptVersion implements retrievePromptVersion operation.
//
// Retrieve prompt version.
//
// POST /v1/private/prompts/versions/retrieve
func (UnimplementedHandler) RetrievePromptVersion(ctx context.Context, req OptPromptVersionRetrieveDetail) (r RetrievePromptVersionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScoreBatchOfSpans implements scoreBatchOfSpans operation.
//
// Batch feedback scoring for spans.
//
// PUT /v1/private/spans/feedback-scores
func (UnimplementedHandler) ScoreBatchOfSpans(ctx context.Context, req OptFeedbackScoreBatch) error {
	return ht.ErrNotImplemented
}

// ScoreBatchOfThreads implements scoreBatchOfThreads operation.
//
// Batch feedback scoring for threads.
//
// PUT /v1/private/traces/threads/feedback-scores
func (UnimplementedHandler) ScoreBatchOfThreads(ctx context.Context, req OptFeedbackScoreBatchThread) error {
	return ht.ErrNotImplemented
}

// ScoreBatchOfTraces implements scoreBatchOfTraces operation.
//
// Batch feedback scoring for traces.
//
// PUT /v1/private/traces/feedback-scores
func (UnimplementedHandler) ScoreBatchOfTraces(ctx context.Context, req OptFeedbackScoreBatch) error {
	return ht.ErrNotImplemented
}

// StartMultiPartUpload implements startMultiPartUpload operation.
//
// Start multipart attachment upload.
//
// POST /v1/private/attachment/upload-start
func (UnimplementedHandler) StartMultiPartUpload(ctx context.Context, req OptStartMultipartUploadRequest) (r StartMultiPartUploadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StoreLlmProviderApiKey implements storeLlmProviderApiKey operation.
//
// Store LLM Provider's ApiKey.
//
// POST /v1/private/llm-provider-key
func (UnimplementedHandler) StoreLlmProviderApiKey(ctx context.Context, req OptProviderApiKeyWrite) (r StoreLlmProviderApiKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SubmitWelcomeWizard implements submitWelcomeWizard operation.
//
// Submit welcome wizard with user information.
//
// POST /v1/private/welcome-wizard
func (UnimplementedHandler) SubmitWelcomeWizard(ctx context.Context, req OptWelcomeWizardSubmission) error {
	return ht.ErrNotImplemented
}

// TestWebhook implements testWebhook operation.
//
// Test alert webhook.
//
// POST /v1/private/alerts/webhooks/tests
func (UnimplementedHandler) TestWebhook(ctx context.Context, req OptAlertWrite) (r TestWebhookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAlert implements updateAlert operation.
//
// Update alert.
//
// PUT /v1/private/alerts/{id}
func (UnimplementedHandler) UpdateAlert(ctx context.Context, req OptAlertWrite, params UpdateAlertParams) (r UpdateAlertRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAnnotationQueue implements updateAnnotationQueue operation.
//
// Update annotation queue by id.
//
// PATCH /v1/private/annotation-queues/{id}
func (UnimplementedHandler) UpdateAnnotationQueue(ctx context.Context, req OptAnnotationQueueUpdate, params UpdateAnnotationQueueParams) (r UpdateAnnotationQueueRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAutomationRuleEvaluator implements updateAutomationRuleEvaluator operation.
//
// Update Automation Rule Evaluator by id.
//
// PATCH /v1/private/automations/evaluators/{id}
func (UnimplementedHandler) UpdateAutomationRuleEvaluator(ctx context.Context, req OptAutomationRuleEvaluatorUpdate, params UpdateAutomationRuleEvaluatorParams) error {
	return ht.ErrNotImplemented
}

// UpdateDashboard implements updateDashboard operation.
//
// Update dashboard by id. Partial updates are supported - only provided fields will be updated.
//
// PATCH /v1/private/dashboards/{dashboardId}
func (UnimplementedHandler) UpdateDashboard(ctx context.Context, req OptDashboardUpdatePublic, params UpdateDashboardParams) (r UpdateDashboardRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDataset implements updateDataset operation.
//
// Update dataset by id.
//
// PUT /v1/private/datasets/{id}
func (UnimplementedHandler) UpdateDataset(ctx context.Context, req OptDatasetUpdate, params UpdateDatasetParams) error {
	return ht.ErrNotImplemented
}

// UpdateDatasetVersion implements updateDatasetVersion operation.
//
// Update a dataset version's change_description and/or add new tags.
//
// PATCH /v1/private/datasets/{id}/versions/hash/{versionHash}
func (UnimplementedHandler) UpdateDatasetVersion(ctx context.Context, req OptDatasetVersionUpdatePublic, params UpdateDatasetVersionParams) (r UpdateDatasetVersionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateExperiment implements updateExperiment operation.
//
// Update experiment by id.
//
// PATCH /v1/private/experiments/{id}
func (UnimplementedHandler) UpdateExperiment(ctx context.Context, req OptExperimentUpdate, params UpdateExperimentParams) (r UpdateExperimentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateFeedbackDefinition implements updateFeedbackDefinition operation.
//
// Update feedback definition by id.
//
// PUT /v1/private/feedback-definitions/{id}
func (UnimplementedHandler) UpdateFeedbackDefinition(ctx context.Context, req OptFeedbackUpdate, params UpdateFeedbackDefinitionParams) error {
	return ht.ErrNotImplemented
}

// UpdateLlmProviderApiKey implements updateLlmProviderApiKey operation.
//
// Update LLM Provider's ApiKey.
//
// PATCH /v1/private/llm-provider-key/{id}
func (UnimplementedHandler) UpdateLlmProviderApiKey(ctx context.Context, req OptProviderApiKeyUpdate, params UpdateLlmProviderApiKeyParams) (r UpdateLlmProviderApiKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOptimizationsById implements updateOptimizationsById operation.
//
// Update optimization by id.
//
// PUT /v1/private/optimizations/{id}
func (UnimplementedHandler) UpdateOptimizationsById(ctx context.Context, req OptOptimizationUpdate, params UpdateOptimizationsByIdParams) error {
	return ht.ErrNotImplemented
}

// UpdateProject implements updateProject operation.
//
// Update project by id.
//
// PATCH /v1/private/projects/{id}
func (UnimplementedHandler) UpdateProject(ctx context.Context, req OptProjectUpdate, params UpdateProjectParams) (r UpdateProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePrompt implements updatePrompt operation.
//
// Update prompt.
//
// PUT /v1/private/prompts/{id}
func (UnimplementedHandler) UpdatePrompt(ctx context.Context, req OptPromptUpdatable, params UpdatePromptParams) (r UpdatePromptRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePromptVersions implements updatePromptVersions operation.
//
// Update one or more prompt versions.
// Note: Prompt versions are immutable by design.
// Only organizational properties, such as tags etc., can be updated.
// Core properties like template and metadata cannot be modified after creation.
// PATCH semantics:
// - non-empty values update the field
// - null values preserve existing field values (no change)
// - empty values explicitly clear the field.
//
// PATCH /v1/private/prompts/versions
func (UnimplementedHandler) UpdatePromptVersions(ctx context.Context, req OptPromptVersionBatchUpdate) (r UpdatePromptVersionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSpan implements updateSpan operation.
//
// Update span by id.
//
// PATCH /v1/private/spans/{id}
func (UnimplementedHandler) UpdateSpan(ctx context.Context, req OptSpanUpdate, params UpdateSpanParams) (r UpdateSpanRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSpanComment implements updateSpanComment operation.
//
// Update span comment by id.
//
// PATCH /v1/private/spans/comments/{commentId}
func (UnimplementedHandler) UpdateSpanComment(ctx context.Context, req OptComment, params UpdateSpanCommentParams) (r UpdateSpanCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateThread implements updateThread operation.
//
// Update thread.
//
// PATCH /v1/private/traces/threads/{threadModelId}
func (UnimplementedHandler) UpdateThread(ctx context.Context, req OptTraceThreadUpdate, params UpdateThreadParams) (r UpdateThreadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateThreadComment implements updateThreadComment operation.
//
// Update thread comment by id.
//
// PATCH /v1/private/traces/threads/comments/{commentId}
func (UnimplementedHandler) UpdateThreadComment(ctx context.Context, req OptComment, params UpdateThreadCommentParams) (r UpdateThreadCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTrace implements updateTrace operation.
//
// Update trace by id.
//
// PATCH /v1/private/traces/{id}
func (UnimplementedHandler) UpdateTrace(ctx context.Context, req OptTraceUpdate, params UpdateTraceParams) error {
	return ht.ErrNotImplemented
}

// UpdateTraceComment implements updateTraceComment operation.
//
// Update trace comment by id.
//
// PATCH /v1/private/traces/comments/{commentId}
func (UnimplementedHandler) UpdateTraceComment(ctx context.Context, req OptComment, params UpdateTraceCommentParams) (r UpdateTraceCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpsertOptimization implements upsertOptimization operation.
//
// Upsert optimization.
//
// PUT /v1/private/optimizations
func (UnimplementedHandler) UpsertOptimization(ctx context.Context, req OptOptimizationWrite) (r *UpsertOptimizationCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// UpsertWorkspaceConfiguration implements upsertWorkspaceConfiguration operation.
//
// Upsert workspace configuration.
//
// PUT /v1/private/workspaces/configurations
func (UnimplementedHandler) UpsertWorkspaceConfiguration(ctx context.Context, req OptWorkspaceConfiguration) (r UpsertWorkspaceConfigurationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Version implements version operation.
//
// GET /is-alive/ver
func (UnimplementedHandler) Version(ctx context.Context) (r *VersionDefStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}
