// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"hash/fnv"
)

// Hash computes a hash value for ColumnCompare using FNV-1a.
// Equal objects must produce equal hashes.
func (a ColumnCompare) Hash() uint64 {
	h := fnv.New64a()

	// Hash optional field: Name
	if a.Name.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.Name.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash array field: Types
	for _, item := range a.Types {
		h.Write([]byte(fmt.Sprintf("%v", item)))
	}
	// Hash optional field: FilterFieldPrefix
	if a.FilterFieldPrefix.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.FilterFieldPrefix.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash optional field: FilterField
	if a.FilterField.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.FilterField.Value)))
	} else {
		h.Write([]byte{0})
	}
	return h.Sum64()
}
