// Code generated by ogen, DO NOT EDIT.

package api

import "github.com/ogen-go/ogen/validate"

// Equal compares two ColumnCompare instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a ColumnCompare) Equal(b ColumnCompare, depth int) bool {
	if depth > 10 {
		panic(&validate.DepthLimitError{
			MaxDepth: 10,
			TypeName: "ColumnCompare",
		})
	}

	// Compare optional field: Name
	if a.Name.Set != b.Name.Set {
		return false
	}
	if a.Name.Set {
		if a.Name.Value != b.Name.Value {
			return false
		}
	}
	// Compare array field: Types
	if len(a.Types) != len(b.Types) {
		return false
	}
	for i := range a.Types {
		if a.Types[i] != b.Types[i] {
			return false
		}
	}
	// Compare optional field: FilterFieldPrefix
	if a.FilterFieldPrefix.Set != b.FilterFieldPrefix.Set {
		return false
	}
	if a.FilterFieldPrefix.Set {
		if a.FilterFieldPrefix.Value != b.FilterFieldPrefix.Value {
			return false
		}
	}
	// Compare optional field: FilterField
	if a.FilterField.Set != b.FilterField.Set {
		return false
	}
	if a.FilterField.Set {
		if a.FilterField.Value != b.FilterField.Value {
			return false
		}
	}
	return true
}
