// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"hash/fnv"
)

// Hash computes a hash value for FeedbackScore using FNV-1a.
// Equal objects must produce equal hashes.
func (a FeedbackScore) Hash() uint64 {
	h := fnv.New64a()

	// Hash primitive field: Name
	h.Write([]byte(fmt.Sprintf("%v", a.Name)))
	// Hash optional field: CategoryName
	if a.CategoryName.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.CategoryName.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash primitive field: Value
	h.Write([]byte(fmt.Sprintf("%v", a.Value)))
	// Hash optional field: Reason
	if a.Reason.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.Reason.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash primitive field: Source
	h.Write([]byte(fmt.Sprintf("%v", a.Source)))
	// Hash optional field: CreatedAt
	if a.CreatedAt.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.CreatedAt.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash optional field: LastUpdatedAt
	if a.LastUpdatedAt.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.LastUpdatedAt.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash optional field: CreatedBy
	if a.CreatedBy.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.CreatedBy.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash optional field: LastUpdatedBy
	if a.LastUpdatedBy.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.LastUpdatedBy.Value)))
	} else {
		h.Write([]byte{0})
	}
	// Hash optional field: ValueByAuthor
	if a.ValueByAuthor.Set {
		h.Write([]byte{1})
		h.Write([]byte(fmt.Sprintf("%v", a.ValueByAuthor.Value)))
	} else {
		h.Write([]byte{0})
	}
	return h.Sum64()
}
