// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddItemsToAnnotationQueue implements addItemsToAnnotationQueue operation.
	//
	// Add traces or threads to annotation queue.
	//
	// POST /v1/private/annotation-queues/{id}/items/add
	AddItemsToAnnotationQueue(ctx context.Context, req OptAnnotationQueueItemIds, params AddItemsToAnnotationQueueParams) (AddItemsToAnnotationQueueRes, error)
	// AddSpanComment implements addSpanComment operation.
	//
	// Add span comment.
	//
	// POST /v1/private/spans/{id}/comments
	AddSpanComment(ctx context.Context, req OptComment, params AddSpanCommentParams) (*AddSpanCommentCreated, error)
	// AddSpanFeedbackScore implements addSpanFeedbackScore operation.
	//
	// Add span feedback score.
	//
	// PUT /v1/private/spans/{id}/feedback-scores
	AddSpanFeedbackScore(ctx context.Context, req OptFeedbackScore, params AddSpanFeedbackScoreParams) error
	// AddThreadComment implements addThreadComment operation.
	//
	// Add thread comment.
	//
	// POST /v1/private/traces/threads/{id}/comments
	AddThreadComment(ctx context.Context, req OptComment, params AddThreadCommentParams) (*AddThreadCommentCreated, error)
	// AddTraceComment implements addTraceComment operation.
	//
	// Add trace comment.
	//
	// POST /v1/private/traces/{id}/comments
	AddTraceComment(ctx context.Context, req OptComment, params AddTraceCommentParams) (*AddTraceCommentCreated, error)
	// AddTraceFeedbackScore implements addTraceFeedbackScore operation.
	//
	// Add trace feedback score.
	//
	// PUT /v1/private/traces/{id}/feedback-scores
	AddTraceFeedbackScore(ctx context.Context, req OptFeedbackScore, params AddTraceFeedbackScoreParams) error
	// AttachmentList implements attachmentList operation.
	//
	// Attachments list for entity.
	//
	// GET /v1/private/attachment/list
	AttachmentList(ctx context.Context, params AttachmentListParams) (AttachmentListRes, error)
	// BatchUpdateDatasetItems implements batchUpdateDatasetItems operation.
	//
	// Update multiple dataset items.
	//
	// PATCH /v1/private/datasets/items/batch
	BatchUpdateDatasetItems(ctx context.Context, req OptDatasetItemBatchUpdate) (BatchUpdateDatasetItemsRes, error)
	// BatchUpdateSpans implements batchUpdateSpans operation.
	//
	// Update multiple spans.
	//
	// PATCH /v1/private/spans/batch
	BatchUpdateSpans(ctx context.Context, req OptSpanBatchUpdate) (BatchUpdateSpansRes, error)
	// BatchUpdateThreads implements batchUpdateThreads operation.
	//
	// Update multiple threads.
	//
	// PATCH /v1/private/traces/threads/batch
	BatchUpdateThreads(ctx context.Context, req OptTraceThreadBatchUpdate) (BatchUpdateThreadsRes, error)
	// BatchUpdateTraces implements batchUpdateTraces operation.
	//
	// Update multiple traces.
	//
	// PATCH /v1/private/traces/batch
	BatchUpdateTraces(ctx context.Context, req OptTraceBatchUpdate) (BatchUpdateTracesRes, error)
	// CancelStudioOptimizations implements cancelStudioOptimizations operation.
	//
	// Cancel Studio optimizations by id.
	//
	// GET /v1/private/optimizations/studio/{id}/cancel
	CancelStudioOptimizations(ctx context.Context, params CancelStudioOptimizationsParams) error
	// CheckAccess implements checkAccess operation.
	//
	// Check user access to workspace.
	//
	// POST /v1/private/auth
	CheckAccess(ctx context.Context, req *AuthDetailsHolder) (CheckAccessRes, error)
	// CloseTraceThread implements closeTraceThread operation.
	//
	// Close one or multiple trace threads. Supports both single thread_id and multiple thread_ids for
	// batch operations.
	//
	// PUT /v1/private/traces/threads/close
	CloseTraceThread(ctx context.Context, req OptTraceThreadBatchIdentifier) (CloseTraceThreadRes, error)
	// CompareDatasetVersions implements compareDatasetVersions operation.
	//
	// Compare the latest committed dataset version with the current draft state. This endpoint provides
	// insights into changes made since the last version was committed. The comparison calculates
	// additions, modifications, deletions, and unchanged items between the latest version snapshot and
	// current draft.
	//
	// GET /v1/private/datasets/{id}/versions/diff
	CompareDatasetVersions(ctx context.Context, params CompareDatasetVersionsParams) (CompareDatasetVersionsRes, error)
	// CompleteMultiPartUpload implements completeMultiPartUpload operation.
	//
	// Complete multipart attachment upload.
	//
	// POST /v1/private/attachment/upload-complete
	CompleteMultiPartUpload(ctx context.Context, req OptCompleteMultipartUploadRequest) (CompleteMultiPartUploadRes, error)
	// CostsSummary implements costsSummary operation.
	//
	// Get costs summary.
	//
	// POST /v1/private/workspaces/costs/summaries
	CostsSummary(ctx context.Context, req OptWorkspaceMetricsSummaryRequest) (CostsSummaryRes, error)
	// CreateAlert implements createAlert operation.
	//
	// Create alert.
	//
	// POST /v1/private/alerts
	CreateAlert(ctx context.Context, req OptAlertWrite) (CreateAlertRes, error)
	// CreateAnnotationQueue implements createAnnotationQueue operation.
	//
	// Create annotation queue for human annotation workflows.
	//
	// POST /v1/private/annotation-queues
	CreateAnnotationQueue(ctx context.Context, req OptAnnotationQueueWrite) (CreateAnnotationQueueRes, error)
	// CreateAnnotationQueueBatch implements createAnnotationQueueBatch operation.
	//
	// Create multiple annotation queues for human annotation workflows.
	//
	// POST /v1/private/annotation-queues/batch
	CreateAnnotationQueueBatch(ctx context.Context, req OptAnnotationQueueBatchWrite) (CreateAnnotationQueueBatchRes, error)
	// CreateAutomationRuleEvaluator implements createAutomationRuleEvaluator operation.
	//
	// Create automation rule evaluator.
	//
	// POST /v1/private/automations/evaluators
	CreateAutomationRuleEvaluator(ctx context.Context, req OptAutomationRuleEvaluatorWrite) (*CreateAutomationRuleEvaluatorCreated, error)
	// CreateChatCompletions implements createChatCompletions operation.
	//
	// Create chat completions.
	//
	// POST /v1/private/chat/completions
	CreateChatCompletions(ctx context.Context, req OptChatCompletionRequest) (*ChatCompletionResponse, error)
	// CreateDashboard implements createDashboard operation.
	//
	// Create a new dashboard in a workspace.
	//
	// POST /v1/private/dashboards
	CreateDashboard(ctx context.Context, req OptDashboardWrite) (*DashboardPublicHeaders, error)
	// CreateDataset implements createDataset operation.
	//
	// Create dataset.
	//
	// POST /v1/private/datasets
	CreateDataset(ctx context.Context, req OptDatasetWrite) (*CreateDatasetCreated, error)
	// CreateDatasetItemsFromCsv implements createDatasetItemsFromCsv operation.
	//
	// Create dataset items from uploaded CSV file. CSV should have headers in the first row. Processing
	// happens asynchronously in batches.
	//
	// POST /v1/private/datasets/items/from-csv
	CreateDatasetItemsFromCsv(ctx context.Context, req OptCreateDatasetItemsFromCsvReq) (CreateDatasetItemsFromCsvRes, error)
	// CreateDatasetItemsFromSpans implements createDatasetItemsFromSpans operation.
	//
	// Create dataset items from spans with enriched metadata.
	//
	// POST /v1/private/datasets/{dataset_id}/items/from-spans
	CreateDatasetItemsFromSpans(ctx context.Context, req OptCreateDatasetItemsFromSpansRequest, params CreateDatasetItemsFromSpansParams) error
	// CreateDatasetItemsFromTraces implements createDatasetItemsFromTraces operation.
	//
	// Create dataset items from traces with enriched metadata.
	//
	// POST /v1/private/datasets/{dataset_id}/items/from-traces
	CreateDatasetItemsFromTraces(ctx context.Context, req OptCreateDatasetItemsFromTracesRequest, params CreateDatasetItemsFromTracesParams) error
	// CreateDatasetVersion implements createDatasetVersion operation.
	//
	// Create a new immutable version of the dataset by snapshotting the current state.
	//
	// POST /v1/private/datasets/{id}/versions
	CreateDatasetVersion(ctx context.Context, req OptDatasetVersionCreatePublic, params CreateDatasetVersionParams) (CreateDatasetVersionRes, error)
	// CreateExperiment implements createExperiment operation.
	//
	// Create experiment.
	//
	// POST /v1/private/experiments
	CreateExperiment(ctx context.Context, req OptExperimentWrite) (*CreateExperimentCreated, error)
	// CreateExperimentItems implements createExperimentItems operation.
	//
	// Create experiment items.
	//
	// POST /v1/private/experiments/items
	CreateExperimentItems(ctx context.Context, req OptExperimentItemsBatch) error
	// CreateFeedbackDefinition implements createFeedbackDefinition operation.
	//
	// Get feedback definition.
	//
	// POST /v1/private/feedback-definitions
	CreateFeedbackDefinition(ctx context.Context, req OptFeedbackCreate) (*CreateFeedbackDefinitionCreated, error)
	// CreateGuardrails implements createGuardrails operation.
	//
	// Batch guardrails for traces.
	//
	// POST /v1/private/guardrails
	CreateGuardrails(ctx context.Context, req OptGuardrailBatchWrite) error
	// CreateOptimization implements createOptimization operation.
	//
	// Create optimization.
	//
	// POST /v1/private/optimizations
	CreateOptimization(ctx context.Context, req OptOptimizationWrite) (*CreateOptimizationCreated, error)
	// CreateOrUpdateDatasetItems implements createOrUpdateDatasetItems operation.
	//
	// Create/update dataset items based on dataset item id.
	//
	// PUT /v1/private/datasets/items
	CreateOrUpdateDatasetItems(ctx context.Context, req OptDatasetItemBatchWrite) error
	// CreateProject implements createProject operation.
	//
	// Create project.
	//
	// POST /v1/private/projects
	CreateProject(ctx context.Context, req OptProjectWrite) (CreateProjectRes, error)
	// CreatePrompt implements createPrompt operation.
	//
	// Create prompt.
	//
	// POST /v1/private/prompts
	CreatePrompt(ctx context.Context, req OptPromptWrite) (CreatePromptRes, error)
	// CreatePromptVersion implements createPromptVersion operation.
	//
	// Create prompt version.
	//
	// POST /v1/private/prompts/versions
	CreatePromptVersion(ctx context.Context, req OptCreatePromptVersionDetail) (CreatePromptVersionRes, error)
	// CreateSpan implements createSpan operation.
	//
	// Create span.
	//
	// POST /v1/private/spans
	CreateSpan(ctx context.Context, req OptSpanWrite) (CreateSpanRes, error)
	// CreateSpans implements createSpans operation.
	//
	// Create spans.
	//
	// POST /v1/private/spans/batch
	CreateSpans(ctx context.Context, req OptSpanBatchWrite) error
	// CreateTrace implements createTrace operation.
	//
	// Get trace.
	//
	// POST /v1/private/traces
	CreateTrace(ctx context.Context, req OptTraceWrite) (*CreateTraceCreated, error)
	// CreateTraces implements createTraces operation.
	//
	// Create traces.
	//
	// POST /v1/private/traces/batch
	CreateTraces(ctx context.Context, req OptTraceBatchWrite) error
	// CreateVersionTag implements createVersionTag operation.
	//
	// Add a tag to a specific dataset version for easy reference (e.g., 'baseline', 'v1.0', 'production').
	//
	// POST /v1/private/datasets/{id}/versions/hash/{versionHash}/tags
	CreateVersionTag(ctx context.Context, req OptDatasetVersionTag, params CreateVersionTagParams) (CreateVersionTagRes, error)
	// DeleteAlertBatch implements deleteAlertBatch operation.
	//
	// Delete multiple alerts by their IDs.
	//
	// POST /v1/private/alerts/delete
	DeleteAlertBatch(ctx context.Context, req OptBatchDelete) (DeleteAlertBatchRes, error)
	// DeleteAnnotationQueueBatch implements deleteAnnotationQueueBatch operation.
	//
	// Delete multiple annotation queues by their IDs.
	//
	// POST /v1/private/annotation-queues/delete
	DeleteAnnotationQueueBatch(ctx context.Context, req OptBatchDelete) (DeleteAnnotationQueueBatchRes, error)
	// DeleteAttachments implements deleteAttachments operation.
	//
	// Delete attachments.
	//
	// POST /v1/private/attachment/delete
	DeleteAttachments(ctx context.Context, req OptCompleteMultipartUploadRequest) (DeleteAttachmentsRes, error)
	// DeleteAutomationRuleEvaluatorBatch implements deleteAutomationRuleEvaluatorBatch operation.
	//
	// Delete automation rule evaluators batch.
	//
	// POST /v1/private/automations/evaluators/delete
	DeleteAutomationRuleEvaluatorBatch(ctx context.Context, req OptBatchDelete, params DeleteAutomationRuleEvaluatorBatchParams) error
	// DeleteDashboard implements deleteDashboard operation.
	//
	// Delete dashboard by id.
	//
	// DELETE /v1/private/dashboards/{dashboardId}
	DeleteDashboard(ctx context.Context, params DeleteDashboardParams) error
	// DeleteDashboardsBatch implements deleteDashboardsBatch operation.
	//
	// Delete dashboards batch.
	//
	// POST /v1/private/dashboards/delete-batch
	DeleteDashboardsBatch(ctx context.Context, req OptBatchDelete) error
	// DeleteDataset implements deleteDataset operation.
	//
	// Delete dataset by id.
	//
	// DELETE /v1/private/datasets/{id}
	DeleteDataset(ctx context.Context, params DeleteDatasetParams) error
	// DeleteDatasetByName implements deleteDatasetByName operation.
	//
	// Delete dataset by name.
	//
	// POST /v1/private/datasets/delete
	DeleteDatasetByName(ctx context.Context, req OptDatasetIdentifier) error
	// DeleteDatasetItems implements deleteDatasetItems operation.
	//
	// Delete dataset items using one of two modes:
	// 1. **Delete by IDs**: Provide 'item_ids' to delete specific items by their IDs
	// 2. **Delete by filters**: Provide 'dataset_id' with optional 'filters' to delete items matching
	// criteria
	// When using filters, an empty 'filters' array will delete all items in the specified dataset.
	//
	// POST /v1/private/datasets/items/delete
	DeleteDatasetItems(ctx context.Context, req OptDatasetItemsDelete) (DeleteDatasetItemsRes, error)
	// DeleteDatasetsBatch implements deleteDatasetsBatch operation.
	//
	// Delete datasets batch.
	//
	// POST /v1/private/datasets/delete-batch
	DeleteDatasetsBatch(ctx context.Context, req OptBatchDelete) error
	// DeleteExperimentItems implements deleteExperimentItems operation.
	//
	// Delete experiment items.
	//
	// POST /v1/private/experiments/items/delete
	DeleteExperimentItems(ctx context.Context, req OptExperimentItemsDelete) error
	// DeleteExperimentsById implements deleteExperimentsById operation.
	//
	// Delete experiments by id.
	//
	// POST /v1/private/experiments/delete
	DeleteExperimentsById(ctx context.Context, req OptDeleteIdsHolder) error
	// DeleteFeedbackDefinitionById implements deleteFeedbackDefinitionById operation.
	//
	// Delete feedback definition by id.
	//
	// DELETE /v1/private/feedback-definitions/{id}
	DeleteFeedbackDefinitionById(ctx context.Context, params DeleteFeedbackDefinitionByIdParams) (DeleteFeedbackDefinitionByIdRes, error)
	// DeleteFeedbackDefinitionsBatch implements deleteFeedbackDefinitionsBatch operation.
	//
	// Delete feedback definitions batch.
	//
	// POST /v1/private/feedback-definitions/delete
	DeleteFeedbackDefinitionsBatch(ctx context.Context, req OptBatchDelete) (DeleteFeedbackDefinitionsBatchRes, error)
	// DeleteLlmProviderApiKeysBatch implements deleteLlmProviderApiKeysBatch operation.
	//
	// Delete LLM Provider's ApiKeys batch.
	//
	// POST /v1/private/llm-provider-key/delete
	DeleteLlmProviderApiKeysBatch(ctx context.Context, req OptBatchDelete) error
	// DeleteOptimizationsById implements deleteOptimizationsById operation.
	//
	// Delete optimizations by id.
	//
	// POST /v1/private/optimizations/delete
	DeleteOptimizationsById(ctx context.Context, req OptDeleteIdsHolder) error
	// DeleteProjectById implements deleteProjectById operation.
	//
	// Delete project by id.
	//
	// DELETE /v1/private/projects/{id}
	DeleteProjectById(ctx context.Context, params DeleteProjectByIdParams) (DeleteProjectByIdRes, error)
	// DeleteProjectsBatch implements deleteProjectsBatch operation.
	//
	// Delete projects batch.
	//
	// POST /v1/private/projects/delete
	DeleteProjectsBatch(ctx context.Context, req OptBatchDelete) error
	// DeletePrompt implements deletePrompt operation.
	//
	// Delete prompt.
	//
	// DELETE /v1/private/prompts/{id}
	DeletePrompt(ctx context.Context, params DeletePromptParams) error
	// DeletePromptsBatch implements deletePromptsBatch operation.
	//
	// Delete prompts batch.
	//
	// POST /v1/private/prompts/delete
	DeletePromptsBatch(ctx context.Context, req OptBatchDelete) error
	// DeleteSpanById implements deleteSpanById operation.
	//
	// Delete span by id.
	//
	// DELETE /v1/private/spans/{id}
	DeleteSpanById(ctx context.Context, params DeleteSpanByIdParams) (DeleteSpanByIdRes, error)
	// DeleteSpanComments implements deleteSpanComments operation.
	//
	// Delete span comments.
	//
	// POST /v1/private/spans/comments/delete
	DeleteSpanComments(ctx context.Context, req OptBatchDelete) error
	// DeleteSpanFeedbackScore implements deleteSpanFeedbackScore operation.
	//
	// Delete span feedback score.
	//
	// POST /v1/private/spans/{id}/feedback-scores/delete
	DeleteSpanFeedbackScore(ctx context.Context, req OptDeleteFeedbackScore, params DeleteSpanFeedbackScoreParams) error
	// DeleteThreadComments implements deleteThreadComments operation.
	//
	// Delete thread comments.
	//
	// POST /v1/private/traces/threads/comments/delete
	DeleteThreadComments(ctx context.Context, req OptBatchDelete) error
	// DeleteThreadFeedbackScores implements deleteThreadFeedbackScores operation.
	//
	// Delete thread feedback scores.
	//
	// POST /v1/private/traces/threads/feedback-scores/delete
	DeleteThreadFeedbackScores(ctx context.Context, req OptDeleteThreadFeedbackScores) error
	// DeleteTraceById implements deleteTraceById operation.
	//
	// Delete trace by id.
	//
	// DELETE /v1/private/traces/{id}
	DeleteTraceById(ctx context.Context, params DeleteTraceByIdParams) error
	// DeleteTraceComments implements deleteTraceComments operation.
	//
	// Delete trace comments.
	//
	// POST /v1/private/traces/comments/delete
	DeleteTraceComments(ctx context.Context, req OptBatchDelete) error
	// DeleteTraceFeedbackScore implements deleteTraceFeedbackScore operation.
	//
	// Delete trace feedback score.
	//
	// POST /v1/private/traces/{id}/feedback-scores/delete
	DeleteTraceFeedbackScore(ctx context.Context, req OptDeleteFeedbackScore, params DeleteTraceFeedbackScoreParams) error
	// DeleteTraceThreads implements deleteTraceThreads operation.
	//
	// Delete trace threads.
	//
	// POST /v1/private/traces/threads/delete
	DeleteTraceThreads(ctx context.Context, req OptDeleteTraceThreads) error
	// DeleteTraces implements deleteTraces operation.
	//
	// Delete traces.
	//
	// POST /v1/private/traces/delete
	DeleteTraces(ctx context.Context, req OptBatchDelete) error
	// DeleteVersionTag implements deleteVersionTag operation.
	//
	// Remove a tag from a dataset version. The version itself is not deleted, only the tag reference.
	//
	// DELETE /v1/private/datasets/{id}/versions/{versionHash}/tags/{tag}
	DeleteVersionTag(ctx context.Context, params DeleteVersionTagParams) error
	// DeleteWorkspaceConfiguration implements deleteWorkspaceConfiguration operation.
	//
	// Delete workspace configuration.
	//
	// DELETE /v1/private/workspaces/configurations
	DeleteWorkspaceConfiguration(ctx context.Context) (DeleteWorkspaceConfigurationRes, error)
	// EvaluateSpans implements evaluateSpans operation.
	//
	// Manually trigger evaluation rules on selected spans. Bypasses sampling and enqueues all specified
	// spans for evaluation.
	//
	// POST /v1/private/manual-evaluation/spans
	EvaluateSpans(ctx context.Context, req OptManualEvaluationRequest) (EvaluateSpansRes, error)
	// EvaluateThreads implements evaluateThreads operation.
	//
	// Manually trigger evaluation rules on selected threads. Bypasses sampling and enqueues all
	// specified threads for evaluation.
	//
	// POST /v1/private/manual-evaluation/threads
	EvaluateThreads(ctx context.Context, req OptManualEvaluationRequest) (EvaluateThreadsRes, error)
	// EvaluateTraces implements evaluateTraces operation.
	//
	// Manually trigger evaluation rules on selected traces. Bypasses sampling and enqueues all specified
	// traces for evaluation.
	//
	// POST /v1/private/manual-evaluation/traces
	EvaluateTraces(ctx context.Context, req OptManualEvaluationRequest) (EvaluateTracesRes, error)
	// ExpandDataset implements expandDataset operation.
	//
	// Generate synthetic dataset samples using LLM based on existing data patterns.
	//
	// POST /v1/private/datasets/{id}/expansions
	ExpandDataset(ctx context.Context, req OptDatasetExpansionWrite, params ExpandDatasetParams) (*DatasetExpansionResponse, error)
	// ExperimentItemsBulk implements experimentItemsBulk operation.
	//
	// Record experiment items in bulk with traces, spans, and feedback scores. Maximum request size is
	// 4MB.
	//
	// PUT /v1/private/experiments/items/bulk
	ExperimentItemsBulk(ctx context.Context, req OptExperimentItemBulkUploadExperimentItemBulkWriteView) (ExperimentItemsBulkRes, error)
	// FindAlerts implements findAlerts operation.
	//
	// Find alerts.
	//
	// GET /v1/private/alerts
	FindAlerts(ctx context.Context, params FindAlertsParams) (*AlertPagePublic, error)
	// FindAnnotationQueues implements findAnnotationQueues operation.
	//
	// Find annotation queues with filtering and sorting.
	//
	// GET /v1/private/annotation-queues
	FindAnnotationQueues(ctx context.Context, params FindAnnotationQueuesParams) (*AnnotationQueuePagePublic, error)
	// FindDashboards implements findDashboards operation.
	//
	// Find dashboards in a workspace.
	//
	// GET /v1/private/dashboards
	FindDashboards(ctx context.Context, params FindDashboardsParams) (*DashboardPagePublic, error)
	// FindDatasetItemsWithExperimentItems implements findDatasetItemsWithExperimentItems operation.
	//
	// Find dataset items with experiment items.
	//
	// GET /v1/private/datasets/{id}/items/experiments/items
	FindDatasetItemsWithExperimentItems(ctx context.Context, params FindDatasetItemsWithExperimentItemsParams) (*DatasetItemPageCompare, error)
	// FindDatasets implements findDatasets operation.
	//
	// Find datasets.
	//
	// GET /v1/private/datasets
	FindDatasets(ctx context.Context, params FindDatasetsParams) (*DatasetPagePublic, error)
	// FindEvaluators implements findEvaluators operation.
	//
	// Find project Evaluators.
	//
	// GET /v1/private/automations/evaluators
	FindEvaluators(ctx context.Context, params FindEvaluatorsParams) (*AutomationRuleEvaluatorPagePublic, error)
	// FindExperimentGroups implements findExperimentGroups operation.
	//
	// Find experiments grouped by specified fields.
	//
	// GET /v1/private/experiments/groups
	FindExperimentGroups(ctx context.Context, params FindExperimentGroupsParams) (FindExperimentGroupsRes, error)
	// FindExperimentGroupsAggregations implements findExperimentGroupsAggregations operation.
	//
	// Find experiments grouped by specified fields with aggregation metrics.
	//
	// GET /v1/private/experiments/groups/aggregations
	FindExperimentGroupsAggregations(ctx context.Context, params FindExperimentGroupsAggregationsParams) (FindExperimentGroupsAggregationsRes, error)
	// FindExperiments implements findExperiments operation.
	//
	// Find experiments.
	//
	// GET /v1/private/experiments
	FindExperiments(ctx context.Context, params FindExperimentsParams) (FindExperimentsRes, error)
	// FindFeedbackDefinitions implements findFeedbackDefinitions operation.
	//
	// Find Feedback definitions.
	//
	// GET /v1/private/feedback-definitions
	FindFeedbackDefinitions(ctx context.Context, params FindFeedbackDefinitionsParams) (*FeedbackDefinitionPagePublic, error)
	// FindFeedbackScoreNames implements findFeedbackScoreNames operation.
	//
	// Find Feedback Score names.
	//
	// GET /v1/private/experiments/feedback-scores/names
	FindFeedbackScoreNames(ctx context.Context, params FindFeedbackScoreNamesParams) ([]string, error)
	// FindFeedbackScoreNames1 implements findFeedbackScoreNames_1 operation.
	//
	// Find Feedback Score names.
	//
	// GET /v1/private/spans/feedback-scores/names
	FindFeedbackScoreNames1(ctx context.Context, params FindFeedbackScoreNames1Params) ([]string, error)
	// FindFeedbackScoreNames2 implements findFeedbackScoreNames_2 operation.
	//
	// Find Feedback Score names.
	//
	// GET /v1/private/traces/feedback-scores/names
	FindFeedbackScoreNames2(ctx context.Context, params FindFeedbackScoreNames2Params) ([]string, error)
	// FindFeedbackScoreNamesByProjectIds implements findFeedbackScoreNamesByProjectIds operation.
	//
	// Find Feedback Score names By Project Ids.
	//
	// GET /v1/private/projects/feedback-scores/names
	FindFeedbackScoreNamesByProjectIds(ctx context.Context, params FindFeedbackScoreNamesByProjectIdsParams) (*FeedbackScoreNames, error)
	// FindLlmProviderKeys implements findLlmProviderKeys operation.
	//
	// Find LLM Provider's ApiKeys.
	//
	// GET /v1/private/llm-provider-key
	FindLlmProviderKeys(ctx context.Context) (*ProviderApiKeyPagePublic, error)
	// FindOptimizations implements findOptimizations operation.
	//
	// Find optimizations.
	//
	// GET /v1/private/optimizations
	FindOptimizations(ctx context.Context, params FindOptimizationsParams) (FindOptimizationsRes, error)
	// FindProjects implements findProjects operation.
	//
	// Find projects.
	//
	// GET /v1/private/projects
	FindProjects(ctx context.Context, params FindProjectsParams) (*ProjectPagePublic, error)
	// FindStudioOptimizations implements findStudioOptimizations operation.
	//
	// Find Studio optimizations.
	//
	// GET /v1/private/optimizations/studio
	FindStudioOptimizations(ctx context.Context, params FindStudioOptimizationsParams) (FindStudioOptimizationsRes, error)
	// FindTraceThreadsFeedbackScoreNames implements findTraceThreadsFeedbackScoreNames operation.
	//
	// Find Trace Threads Feedback Score names.
	//
	// GET /v1/private/traces/threads/feedback-scores/names
	FindTraceThreadsFeedbackScoreNames(ctx context.Context, params FindTraceThreadsFeedbackScoreNamesParams) ([]string, error)
	// FinishExperiments implements finishExperiments operation.
	//
	// Finish experiments and trigger alert events.
	//
	// POST /v1/private/experiments/finish
	FinishExperiments(ctx context.Context, req OptDeleteIdsHolder) (FinishExperimentsRes, error)
	// GetAlertById implements getAlertById operation.
	//
	// Get Alert by id.
	//
	// GET /v1/private/alerts/{id}
	GetAlertById(ctx context.Context, params GetAlertByIdParams) (GetAlertByIdRes, error)
	// GetAnnotationQueueById implements getAnnotationQueueById operation.
	//
	// Get annotation queue by id.
	//
	// GET /v1/private/annotation-queues/{id}
	GetAnnotationQueueById(ctx context.Context, params GetAnnotationQueueByIdParams) (GetAnnotationQueueByIdRes, error)
	// GetCost implements getCost operation.
	//
	// Get cost daily data.
	//
	// POST /v1/private/workspaces/costs
	GetCost(ctx context.Context, req OptWorkspaceMetricsSummaryRequest) (GetCostRes, error)
	// GetDashboardById implements getDashboardById operation.
	//
	// Get dashboard by id.
	//
	// GET /v1/private/dashboards/{dashboardId}
	GetDashboardById(ctx context.Context, params GetDashboardByIdParams) (GetDashboardByIdRes, error)
	// GetDatasetBiInfo implements getDatasetBiInfo operation.
	//
	// Get datasets information for BI events per user per workspace.
	//
	// GET /v1/internal/usage/bi-datasets
	GetDatasetBiInfo(ctx context.Context) (*BiInformationResponse, error)
	// GetDatasetById implements getDatasetById operation.
	//
	// Get dataset by id.
	//
	// GET /v1/private/datasets/{id}
	GetDatasetById(ctx context.Context, params GetDatasetByIdParams) (*DatasetPublic, error)
	// GetDatasetByIdentifier implements getDatasetByIdentifier operation.
	//
	// Get dataset by name.
	//
	// POST /v1/private/datasets/retrieve
	GetDatasetByIdentifier(ctx context.Context, req OptDatasetIdentifierPublic) (*DatasetPublic, error)
	// GetDatasetExperimentItemsStats implements getDatasetExperimentItemsStats operation.
	//
	// Get experiment items stats for dataset.
	//
	// GET /v1/private/datasets/{id}/items/experiments/items/stats
	GetDatasetExperimentItemsStats(ctx context.Context, params GetDatasetExperimentItemsStatsParams) (*ProjectStatsPublic, error)
	// GetDatasetItemById implements getDatasetItemById operation.
	//
	// Get dataset item by id.
	//
	// GET /v1/private/datasets/items/{itemId}
	GetDatasetItemById(ctx context.Context, params GetDatasetItemByIdParams) (*DatasetItemPublic, error)
	// GetDatasetItems implements getDatasetItems operation.
	//
	// Get dataset items.
	//
	// GET /v1/private/datasets/{id}/items
	GetDatasetItems(ctx context.Context, params GetDatasetItemsParams) (*DatasetItemPagePublic, error)
	// GetDatasetItemsOutputColumns implements getDatasetItemsOutputColumns operation.
	//
	// Get dataset items output columns.
	//
	// GET /v1/private/datasets/{id}/items/experiments/items/output/columns
	GetDatasetItemsOutputColumns(ctx context.Context, params GetDatasetItemsOutputColumnsParams) (*PageColumns, error)
	// GetEvaluatorById implements getEvaluatorById operation.
	//
	// Get automation rule by id.
	//
	// GET /v1/private/automations/evaluators/{id}
	GetEvaluatorById(ctx context.Context, params GetEvaluatorByIdParams) (*AutomationRuleEvaluatorPublic, error)
	// GetEvaluatorLogsById implements getEvaluatorLogsById operation.
	//
	// Get automation rule evaluator logs by id.
	//
	// GET /v1/private/automations/evaluators/{id}/logs
	GetEvaluatorLogsById(ctx context.Context, params GetEvaluatorLogsByIdParams) (*LogPage, error)
	// GetExperimentBiInfo implements getExperimentBiInfo operation.
	//
	// Get experiments information for BI events per user per workspace.
	//
	// GET /v1/internal/usage/bi-experiments
	GetExperimentBiInfo(ctx context.Context) (*BiInformationResponse, error)
	// GetExperimentById implements getExperimentById operation.
	//
	// Get experiment by id.
	//
	// GET /v1/private/experiments/{id}
	GetExperimentById(ctx context.Context, params GetExperimentByIdParams) (GetExperimentByIdRes, error)
	// GetExperimentItemById implements getExperimentItemById operation.
	//
	// Get experiment item by id.
	//
	// GET /v1/private/experiments/items/{id}
	GetExperimentItemById(ctx context.Context, params GetExperimentItemByIdParams) (GetExperimentItemByIdRes, error)
	// GetFeedbackDefinitionById implements getFeedbackDefinitionById operation.
	//
	// Get feedback definition by id.
	//
	// GET /v1/private/feedback-definitions/{id}
	GetFeedbackDefinitionById(ctx context.Context, params GetFeedbackDefinitionByIdParams) (*FeedbackPublic, error)
	// GetLlmProviderApiKeyById implements getLlmProviderApiKeyById operation.
	//
	// Get LLM Provider's ApiKey by id.
	//
	// GET /v1/private/llm-provider-key/{id}
	GetLlmProviderApiKeyById(ctx context.Context, params GetLlmProviderApiKeyByIdParams) (GetLlmProviderApiKeyByIdRes, error)
	// GetMetric implements getMetric operation.
	//
	// Get metric daily data.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/private/workspaces/metrics
	GetMetric(ctx context.Context, req OptWorkspaceMetricsSummaryRequest) (GetMetricRes, error)
	// GetOptimizationById implements getOptimizationById operation.
	//
	// Get optimization by id.
	//
	// GET /v1/private/optimizations/{id}
	GetOptimizationById(ctx context.Context, params GetOptimizationByIdParams) (GetOptimizationByIdRes, error)
	// GetProjectById implements getProjectById operation.
	//
	// Get project by id.
	//
	// GET /v1/private/projects/{id}
	GetProjectById(ctx context.Context, params GetProjectByIdParams) (*ProjectPublic, error)
	// GetProjectMetrics implements getProjectMetrics operation.
	//
	// Gets specified metrics for a project.
	//
	// POST /v1/private/projects/{id}/metrics
	GetProjectMetrics(ctx context.Context, req OptProjectMetricRequestPublic, params GetProjectMetricsParams) (GetProjectMetricsRes, error)
	// GetProjectStats implements getProjectStats operation.
	//
	// Get Project Stats.
	//
	// GET /v1/private/projects/stats
	GetProjectStats(ctx context.Context, params GetProjectStatsParams) (*ProjectStatsSummary, error)
	// GetPromptById implements getPromptById operation.
	//
	// Get prompt by id.
	//
	// GET /v1/private/prompts/{id}
	GetPromptById(ctx context.Context, params GetPromptByIdParams) (GetPromptByIdRes, error)
	// GetPromptVersionById implements getPromptVersionById operation.
	//
	// Get prompt version by id.
	//
	// GET /v1/private/prompts/versions/{versionId}
	GetPromptVersionById(ctx context.Context, params GetPromptVersionByIdParams) (GetPromptVersionByIdRes, error)
	// GetPromptVersions implements getPromptVersions operation.
	//
	// Get prompt versions.
	//
	// GET /v1/private/prompts/{id}/versions
	GetPromptVersions(ctx context.Context, params GetPromptVersionsParams) (*PromptVersionPagePublic, error)
	// GetPrompts implements getPrompts operation.
	//
	// Get prompts.
	//
	// GET /v1/private/prompts
	GetPrompts(ctx context.Context, params GetPromptsParams) (*PromptPagePublic, error)
	// GetServiceToggles implements getServiceToggles operation.
	//
	// Get Service Toggles.
	//
	// GET /v1/private/toggles
	GetServiceToggles(ctx context.Context) (*ServiceTogglesConfig, error)
	// GetSpanById implements getSpanById operation.
	//
	// Get span by id.
	//
	// GET /v1/private/spans/{id}
	GetSpanById(ctx context.Context, params GetSpanByIdParams) (GetSpanByIdRes, error)
	// GetSpanComment implements getSpanComment operation.
	//
	// Get span comment.
	//
	// GET /v1/private/spans/{spanId}/comments/{commentId}
	GetSpanComment(ctx context.Context, params GetSpanCommentParams) (GetSpanCommentRes, error)
	// GetSpanStats implements getSpanStats operation.
	//
	// Get span stats.
	//
	// GET /v1/private/spans/stats
	GetSpanStats(ctx context.Context, params GetSpanStatsParams) (*ProjectStatsPublic, error)
	// GetSpansBiInfo implements getSpansBiInfo operation.
	//
	// Get spans information for BI events per user per workspace.
	//
	// GET /v1/internal/usage/bi-spans
	GetSpansBiInfo(ctx context.Context) (*BiInformationResponse, error)
	// GetSpansByProject implements getSpansByProject operation.
	//
	// Get spans by project_name or project_id and optionally by trace_id and/or type.
	//
	// GET /v1/private/spans
	GetSpansByProject(ctx context.Context, params GetSpansByProjectParams) (*SpanPagePublic, error)
	// GetSpansCountForWorkspaces implements getSpansCountForWorkspaces operation.
	//
	// Get spans count on previous day for all available workspaces.
	//
	// GET /v1/internal/usage/workspace-span-counts
	GetSpansCountForWorkspaces(ctx context.Context) (*SpansCountResponse, error)
	// GetStudioOptimizationById implements getStudioOptimizationById operation.
	//
	// Get Studio optimization with config included.
	//
	// GET /v1/private/optimizations/studio/{id}
	GetStudioOptimizationById(ctx context.Context, params GetStudioOptimizationByIdParams) (GetStudioOptimizationByIdRes, error)
	// GetStudioOptimizationLogs implements getStudioOptimizationLogs operation.
	//
	// Get presigned S3 URL for downloading optimization logs.
	//
	// GET /v1/private/optimizations/studio/{id}/logs
	GetStudioOptimizationLogs(ctx context.Context, params GetStudioOptimizationLogsParams) (GetStudioOptimizationLogsRes, error)
	// GetThreadComment implements getThreadComment operation.
	//
	// Get thread comment.
	//
	// GET /v1/private/traces/threads/{threadId}/comments/{commentId}
	GetThreadComment(ctx context.Context, params GetThreadCommentParams) (GetThreadCommentRes, error)
	// GetTraceById implements getTraceById operation.
	//
	// Get trace by id.
	//
	// GET /v1/private/traces/{id}
	GetTraceById(ctx context.Context, params GetTraceByIdParams) (*TracePublic, error)
	// GetTraceComment implements getTraceComment operation.
	//
	// Get trace comment.
	//
	// GET /v1/private/traces/{traceId}/comments/{commentId}
	GetTraceComment(ctx context.Context, params GetTraceCommentParams) (GetTraceCommentRes, error)
	// GetTraceStats implements getTraceStats operation.
	//
	// Get trace stats.
	//
	// GET /v1/private/traces/stats
	GetTraceStats(ctx context.Context, params GetTraceStatsParams) (*ProjectStatsPublic, error)
	// GetTraceThread implements getTraceThread operation.
	//
	// Get trace thread.
	//
	// POST /v1/private/traces/threads/retrieve
	GetTraceThread(ctx context.Context, req OptTraceThreadIdentifier) (GetTraceThreadRes, error)
	// GetTraceThreadStats implements getTraceThreadStats operation.
	//
	// Get trace thread stats.
	//
	// GET /v1/private/traces/threads/stats
	GetTraceThreadStats(ctx context.Context, params GetTraceThreadStatsParams) (*ProjectStatsPublic, error)
	// GetTraceThreads implements getTraceThreads operation.
	//
	// Get trace threads.
	//
	// GET /v1/private/traces/threads
	GetTraceThreads(ctx context.Context, params GetTraceThreadsParams) (*TraceThreadPage, error)
	// GetTracesBiInfo implements getTracesBiInfo operation.
	//
	// Get traces information for BI events per user per workspace.
	//
	// GET /v1/internal/usage/bi-traces
	GetTracesBiInfo(ctx context.Context) (*BiInformationResponse, error)
	// GetTracesByProject implements getTracesByProject operation.
	//
	// Get traces by project_name or project_id.
	//
	// GET /v1/private/traces
	GetTracesByProject(ctx context.Context, params GetTracesByProjectParams) (*TracePagePublic, error)
	// GetTracesCountForWorkspaces implements getTracesCountForWorkspaces operation.
	//
	// Get traces count on previous day for all available workspaces.
	//
	// GET /v1/internal/usage/workspace-trace-counts
	GetTracesCountForWorkspaces(ctx context.Context) (*TraceCountResponse, error)
	// GetWebhookExamples implements getWebhookExamples operation.
	//
	// Get webhook payload examples for all alert event types, optionally filtered by alert type.
	//
	// GET /v1/private/alerts/webhooks/examples
	GetWebhookExamples(ctx context.Context, params GetWebhookExamplesParams) (*WebhookExamples, error)
	// GetWelcomeWizardStatus implements getWelcomeWizardStatus operation.
	//
	// Get welcome wizard tracking status for the current workspace.
	//
	// GET /v1/private/welcome-wizard
	GetWelcomeWizardStatus(ctx context.Context) (*WelcomeWizardTracking, error)
	// GetWorkspaceConfiguration implements getWorkspaceConfiguration operation.
	//
	// Get workspace configuration.
	//
	// GET /v1/private/workspaces/configurations
	GetWorkspaceConfiguration(ctx context.Context) (GetWorkspaceConfigurationRes, error)
	// GetWorkspaceName implements getWorkspaceName operation.
	//
	// User's default workspace name.
	//
	// GET /v1/private/auth/workspace
	GetWorkspaceName(ctx context.Context) (GetWorkspaceNameRes, error)
	// IsAlive implements isAlive operation.
	//
	// GET /is-alive/ping
	IsAlive(ctx context.Context) (*IsAliveDefStatusCode, error)
	// ListDatasetVersions implements listDatasetVersions operation.
	//
	// Get paginated list of versions for a dataset, ordered by creation time (newest first).
	//
	// GET /v1/private/datasets/{id}/versions
	ListDatasetVersions(ctx context.Context, params ListDatasetVersionsParams) (ListDatasetVersionsRes, error)
	// MetricsSummary implements metricsSummary operation.
	//
	// Get metrics summary.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/private/workspaces/metrics/summaries
	MetricsSummary(ctx context.Context, req OptWorkspaceMetricsSummaryRequest) (MetricsSummaryRes, error)
	// OpenTraceThread implements openTraceThread operation.
	//
	// Open trace thread.
	//
	// PUT /v1/private/traces/threads/open
	OpenTraceThread(ctx context.Context, req OptTraceThreadIdentifier) error
	// PatchDatasetItem implements patchDatasetItem operation.
	//
	// Partially update dataset item by id. Only provided fields will be updated.
	//
	// PATCH /v1/private/datasets/items/{itemId}
	PatchDatasetItem(ctx context.Context, req OptDatasetItemWrite, params PatchDatasetItemParams) (PatchDatasetItemRes, error)
	// RemoveItemsFromAnnotationQueue implements removeItemsFromAnnotationQueue operation.
	//
	// Remove items from annotation queue.
	//
	// POST /v1/private/annotation-queues/{id}/items/delete
	RemoveItemsFromAnnotationQueue(ctx context.Context, req OptAnnotationQueueItemIds, params RemoveItemsFromAnnotationQueueParams) (RemoveItemsFromAnnotationQueueRes, error)
	// RestoreDatasetVersion implements restoreDatasetVersion operation.
	//
	// Restores the dataset to a previous version state. All draft items are replaced with items from the
	// specified version. If the version is not the latest, a new version snapshot is created. If the
	// version is the latest, only draft items are replaced (revert functionality).
	//
	// POST /v1/private/datasets/{id}/versions/restore
	RestoreDatasetVersion(ctx context.Context, req OptDatasetVersionRestorePublic, params RestoreDatasetVersionParams) (RestoreDatasetVersionRes, error)
	// RestorePromptVersion implements restorePromptVersion operation.
	//
	// Restore a prompt version by creating a new version with the content from the specified version.
	//
	// POST /v1/private/prompts/{promptId}/versions/{versionId}/restore
	RestorePromptVersion(ctx context.Context, params RestorePromptVersionParams) (RestorePromptVersionRes, error)
	// RetrieveProject implements retrieveProject operation.
	//
	// Retrieve project.
	//
	// POST /v1/private/projects/retrieve
	RetrieveProject(ctx context.Context, req OptProjectRetrieveDetailed) (RetrieveProjectRes, error)
	// RetrievePromptVersion implements retrievePromptVersion operation.
	//
	// Retrieve prompt version.
	//
	// POST /v1/private/prompts/versions/retrieve
	RetrievePromptVersion(ctx context.Context, req OptPromptVersionRetrieveDetail) (RetrievePromptVersionRes, error)
	// ScoreBatchOfSpans implements scoreBatchOfSpans operation.
	//
	// Batch feedback scoring for spans.
	//
	// PUT /v1/private/spans/feedback-scores
	ScoreBatchOfSpans(ctx context.Context, req OptFeedbackScoreBatch) error
	// ScoreBatchOfThreads implements scoreBatchOfThreads operation.
	//
	// Batch feedback scoring for threads.
	//
	// PUT /v1/private/traces/threads/feedback-scores
	ScoreBatchOfThreads(ctx context.Context, req OptFeedbackScoreBatchThread) error
	// ScoreBatchOfTraces implements scoreBatchOfTraces operation.
	//
	// Batch feedback scoring for traces.
	//
	// PUT /v1/private/traces/feedback-scores
	ScoreBatchOfTraces(ctx context.Context, req OptFeedbackScoreBatch) error
	// StartMultiPartUpload implements startMultiPartUpload operation.
	//
	// Start multipart attachment upload.
	//
	// POST /v1/private/attachment/upload-start
	StartMultiPartUpload(ctx context.Context, req OptStartMultipartUploadRequest) (StartMultiPartUploadRes, error)
	// StoreLlmProviderApiKey implements storeLlmProviderApiKey operation.
	//
	// Store LLM Provider's ApiKey.
	//
	// POST /v1/private/llm-provider-key
	StoreLlmProviderApiKey(ctx context.Context, req OptProviderApiKeyWrite) (StoreLlmProviderApiKeyRes, error)
	// SubmitWelcomeWizard implements submitWelcomeWizard operation.
	//
	// Submit welcome wizard with user information.
	//
	// POST /v1/private/welcome-wizard
	SubmitWelcomeWizard(ctx context.Context, req OptWelcomeWizardSubmission) error
	// TestWebhook implements testWebhook operation.
	//
	// Test alert webhook.
	//
	// POST /v1/private/alerts/webhooks/tests
	TestWebhook(ctx context.Context, req OptAlertWrite) (TestWebhookRes, error)
	// UpdateAlert implements updateAlert operation.
	//
	// Update alert.
	//
	// PUT /v1/private/alerts/{id}
	UpdateAlert(ctx context.Context, req OptAlertWrite, params UpdateAlertParams) (UpdateAlertRes, error)
	// UpdateAnnotationQueue implements updateAnnotationQueue operation.
	//
	// Update annotation queue by id.
	//
	// PATCH /v1/private/annotation-queues/{id}
	UpdateAnnotationQueue(ctx context.Context, req OptAnnotationQueueUpdate, params UpdateAnnotationQueueParams) (UpdateAnnotationQueueRes, error)
	// UpdateAutomationRuleEvaluator implements updateAutomationRuleEvaluator operation.
	//
	// Update Automation Rule Evaluator by id.
	//
	// PATCH /v1/private/automations/evaluators/{id}
	UpdateAutomationRuleEvaluator(ctx context.Context, req OptAutomationRuleEvaluatorUpdate, params UpdateAutomationRuleEvaluatorParams) error
	// UpdateDashboard implements updateDashboard operation.
	//
	// Update dashboard by id. Partial updates are supported - only provided fields will be updated.
	//
	// PATCH /v1/private/dashboards/{dashboardId}
	UpdateDashboard(ctx context.Context, req OptDashboardUpdatePublic, params UpdateDashboardParams) (UpdateDashboardRes, error)
	// UpdateDataset implements updateDataset operation.
	//
	// Update dataset by id.
	//
	// PUT /v1/private/datasets/{id}
	UpdateDataset(ctx context.Context, req OptDatasetUpdate, params UpdateDatasetParams) error
	// UpdateDatasetVersion implements updateDatasetVersion operation.
	//
	// Update a dataset version's change_description and/or add new tags.
	//
	// PATCH /v1/private/datasets/{id}/versions/hash/{versionHash}
	UpdateDatasetVersion(ctx context.Context, req OptDatasetVersionUpdatePublic, params UpdateDatasetVersionParams) (UpdateDatasetVersionRes, error)
	// UpdateExperiment implements updateExperiment operation.
	//
	// Update experiment by id.
	//
	// PATCH /v1/private/experiments/{id}
	UpdateExperiment(ctx context.Context, req OptExperimentUpdate, params UpdateExperimentParams) (UpdateExperimentRes, error)
	// UpdateFeedbackDefinition implements updateFeedbackDefinition operation.
	//
	// Update feedback definition by id.
	//
	// PUT /v1/private/feedback-definitions/{id}
	UpdateFeedbackDefinition(ctx context.Context, req OptFeedbackUpdate, params UpdateFeedbackDefinitionParams) error
	// UpdateLlmProviderApiKey implements updateLlmProviderApiKey operation.
	//
	// Update LLM Provider's ApiKey.
	//
	// PATCH /v1/private/llm-provider-key/{id}
	UpdateLlmProviderApiKey(ctx context.Context, req OptProviderApiKeyUpdate, params UpdateLlmProviderApiKeyParams) (UpdateLlmProviderApiKeyRes, error)
	// UpdateOptimizationsById implements updateOptimizationsById operation.
	//
	// Update optimization by id.
	//
	// PUT /v1/private/optimizations/{id}
	UpdateOptimizationsById(ctx context.Context, req OptOptimizationUpdate, params UpdateOptimizationsByIdParams) error
	// UpdateProject implements updateProject operation.
	//
	// Update project by id.
	//
	// PATCH /v1/private/projects/{id}
	UpdateProject(ctx context.Context, req OptProjectUpdate, params UpdateProjectParams) (UpdateProjectRes, error)
	// UpdatePrompt implements updatePrompt operation.
	//
	// Update prompt.
	//
	// PUT /v1/private/prompts/{id}
	UpdatePrompt(ctx context.Context, req OptPromptUpdatable, params UpdatePromptParams) (UpdatePromptRes, error)
	// UpdatePromptVersions implements updatePromptVersions operation.
	//
	// Update one or more prompt versions.
	// Note: Prompt versions are immutable by design.
	// Only organizational properties, such as tags etc., can be updated.
	// Core properties like template and metadata cannot be modified after creation.
	// PATCH semantics:
	// - non-empty values update the field
	// - null values preserve existing field values (no change)
	// - empty values explicitly clear the field.
	//
	// PATCH /v1/private/prompts/versions
	UpdatePromptVersions(ctx context.Context, req OptPromptVersionBatchUpdate) (UpdatePromptVersionsRes, error)
	// UpdateSpan implements updateSpan operation.
	//
	// Update span by id.
	//
	// PATCH /v1/private/spans/{id}
	UpdateSpan(ctx context.Context, req OptSpanUpdate, params UpdateSpanParams) (UpdateSpanRes, error)
	// UpdateSpanComment implements updateSpanComment operation.
	//
	// Update span comment by id.
	//
	// PATCH /v1/private/spans/comments/{commentId}
	UpdateSpanComment(ctx context.Context, req OptComment, params UpdateSpanCommentParams) (UpdateSpanCommentRes, error)
	// UpdateThread implements updateThread operation.
	//
	// Update thread.
	//
	// PATCH /v1/private/traces/threads/{threadModelId}
	UpdateThread(ctx context.Context, req OptTraceThreadUpdate, params UpdateThreadParams) (UpdateThreadRes, error)
	// UpdateThreadComment implements updateThreadComment operation.
	//
	// Update thread comment by id.
	//
	// PATCH /v1/private/traces/threads/comments/{commentId}
	UpdateThreadComment(ctx context.Context, req OptComment, params UpdateThreadCommentParams) (UpdateThreadCommentRes, error)
	// UpdateTrace implements updateTrace operation.
	//
	// Update trace by id.
	//
	// PATCH /v1/private/traces/{id}
	UpdateTrace(ctx context.Context, req OptTraceUpdate, params UpdateTraceParams) error
	// UpdateTraceComment implements updateTraceComment operation.
	//
	// Update trace comment by id.
	//
	// PATCH /v1/private/traces/comments/{commentId}
	UpdateTraceComment(ctx context.Context, req OptComment, params UpdateTraceCommentParams) (UpdateTraceCommentRes, error)
	// UpsertOptimization implements upsertOptimization operation.
	//
	// Upsert optimization.
	//
	// PUT /v1/private/optimizations
	UpsertOptimization(ctx context.Context, req OptOptimizationWrite) (*UpsertOptimizationCreated, error)
	// UpsertWorkspaceConfiguration implements upsertWorkspaceConfiguration operation.
	//
	// Upsert workspace configuration.
	//
	// PUT /v1/private/workspaces/configurations
	UpsertWorkspaceConfiguration(ctx context.Context, req OptWorkspaceConfiguration) (UpsertWorkspaceConfigurationRes, error)
	// Version implements version operation.
	//
	// GET /is-alive/ver
	Version(ctx context.Context) (*VersionDefStatusCode, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
