// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *CreatePromptVersionDetail) setDefaults() {
	{
		val := CreatePromptVersionDetailTemplateStructure("text")
		s.TemplateStructure.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PromptDetail) setDefaults() {
	{
		val := PromptDetailTemplateStructure("text")
		s.TemplateStructure.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PromptPublic) setDefaults() {
	{
		val := PromptPublicTemplateStructure("text")
		s.TemplateStructure.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PromptVersionBatchUpdate) setDefaults() {
	{
		val := bool(false)
		s.MergeTags.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PromptWrite) setDefaults() {
	{
		val := PromptWriteTemplateStructure("text")
		s.TemplateStructure.SetTo(val)
	}
}
