// Code generated by ax-spec. DO NOT EDIT.

package ax

// Capability represents an operation capability for agent introspection.
type Capability string

// Standard capabilities derived from operation semantics.
const (
	CapRead      Capability = "read"
	CapWrite     Capability = "write"
	CapDelete    Capability = "delete"
	CapAdmin     Capability = "admin"
	CapStream    Capability = "stream"
	CapEvaluate  Capability = "evaluate"
	CapAnalytics Capability = "analytics"
)

// OperationCapabilities maps operation IDs to their capabilities.
// Capabilities indicate what an operation can do:
//   - read: retrieves data without modification
//   - write: creates or modifies data
//   - delete: removes data
//   - admin: administrative operations requiring elevated permissions
//   - stream: supports streaming responses
//   - evaluate: performs LLM evaluation
//   - analytics: retrieves analytics/metrics data
var OperationCapabilities = map[string][]Capability{
	// BI/Analytics
	"getDatasetBiInfo":           {CapRead, CapAnalytics},
	"getExperimentBiInfo":        {CapRead, CapAnalytics},
	"getSpansBiInfo":             {CapRead, CapAnalytics},
	"getSpansCountForWorkspaces": {CapRead, CapAnalytics},
	"getTracesBiInfo":            {CapRead, CapAnalytics},
	"getTracesCountForWorkspaces": {CapRead, CapAnalytics},

	// Trace operations
	"findTraces":       {CapRead},
	"getTracesByProject": {CapRead},
	"createTrace":      {CapWrite},
	"createTraces":     {CapWrite},
	"getTraceById":     {CapRead},
	"updateTrace":      {CapWrite},
	"deleteTraceById":  {CapWrite, CapDelete},
	"deleteTraces":     {CapWrite, CapDelete},
	"searchTraces":     {CapRead},
	"getTraceStats":    {CapRead, CapAnalytics},

	// Span operations
	"getSpansByProject": {CapRead},
	"createSpan":        {CapWrite},
	"createSpans":       {CapWrite},
	"getSpanById":       {CapRead},
	"updateSpan":        {CapWrite},
	"deleteSpanById":    {CapWrite, CapDelete},
	"searchSpans":       {CapRead},
	"getSpanStats":      {CapRead, CapAnalytics},

	// Dataset operations
	"findDatasets":     {CapRead},
	"createDataset":    {CapWrite},
	"getDatasetById":   {CapRead},
	"updateDataset":    {CapWrite},
	"deleteDataset":    {CapWrite, CapDelete},
	"deleteDatasetsBatch": {CapWrite, CapDelete},
	"getDatasetItems":  {CapRead},
	"streamDatasetItems": {CapRead, CapStream},

	// Experiment operations
	"findExperiments":       {CapRead},
	"createExperiment":      {CapWrite},
	"getExperimentById":     {CapRead},
	"updateExperiment":      {CapWrite},
	"deleteExperimentsById": {CapWrite, CapDelete},
	"streamExperimentItems": {CapRead, CapStream},
	"streamExperiments":     {CapRead, CapStream},

	// Project operations
	"findProjects":       {CapRead},
	"createProject":      {CapWrite},
	"getProjectById":     {CapRead},
	"updateProject":      {CapWrite},
	"deleteProjectById":  {CapWrite, CapDelete},
	"deleteProjectsBatch": {CapWrite, CapDelete},
	"getProjectMetrics":  {CapRead, CapAnalytics},
	"getProjectStats":    {CapRead, CapAnalytics},

	// Prompt operations
	"getPrompts":           {CapRead},
	"createPrompt":         {CapWrite},
	"getPromptById":        {CapRead},
	"updatePrompt":         {CapWrite},
	"deletePrompt":         {CapWrite, CapDelete},
	"getPromptVersions":    {CapRead},
	"createPromptVersion":  {CapWrite},
	"getPromptVersionById": {CapRead},

	// Evaluation operations
	"evaluateSpans":   {CapWrite, CapEvaluate},
	"evaluateThreads": {CapWrite, CapEvaluate},
	"evaluateTraces":  {CapWrite, CapEvaluate},

	// Evaluator operations
	"findEvaluators":                {CapRead},
	"createAutomationRuleEvaluator": {CapWrite},
	"getEvaluatorById":              {CapRead},
	"updateAutomationRuleEvaluator": {CapWrite},
	"deleteAutomationRuleEvaluatorBatch": {CapWrite, CapDelete},

	// Feedback operations
	"findFeedbackDefinitions":      {CapRead},
	"createFeedbackDefinition":     {CapWrite},
	"getFeedbackDefinitionById":    {CapRead},
	"updateFeedbackDefinition":     {CapWrite},
	"deleteFeedbackDefinitionById": {CapWrite, CapDelete},
	"addSpanFeedbackScore":         {CapWrite},
	"addTraceFeedbackScore":        {CapWrite},

	// Dashboard operations
	"findDashboards":   {CapRead},
	"createDashboard":  {CapWrite},
	"getDashboardById": {CapRead},
	"updateDashboard":  {CapWrite},
	"deleteDashboard":  {CapWrite, CapDelete},

	// Alert operations
	"findAlerts":   {CapRead},
	"createAlert":  {CapWrite},
	"getAlertById": {CapRead},
	"updateAlert":  {CapWrite},
	"deleteAlertBatch": {CapWrite, CapDelete},

	// Attachment operations
	"attachmentList":     {CapRead},
	"downloadAttachment": {CapRead},
	"uploadAttachment":   {CapWrite},
	"deleteAttachments":  {CapWrite, CapDelete},

	// Usage/Cost operations
	"costsSummary":   {CapRead, CapAnalytics},
	"getCost":        {CapRead, CapAnalytics},
	"getMetric":      {CapRead, CapAnalytics},
	"metricsSummary": {CapRead, CapAnalytics},

	// Admin operations
	"getWorkspaceConfiguration":    {CapRead, CapAdmin},
	"upsertWorkspaceConfiguration": {CapWrite, CapAdmin},
	"deleteWorkspaceConfiguration": {CapWrite, CapDelete, CapAdmin},
	"storeLlmProviderApiKey":       {CapWrite, CapAdmin},
	"updateLlmProviderApiKey":      {CapWrite, CapAdmin},
	"deleteLlmProviderApiKeysBatch": {CapWrite, CapDelete, CapAdmin},

	// Health checks
	"isAlive": {CapRead},
	"version": {CapRead},
}

// GetCapabilities returns the capabilities for an operation.
// Returns nil if the operation is not found.
func GetCapabilities(operationID string) []Capability {
	return OperationCapabilities[operationID]
}

// HasCapability checks if an operation has a specific capability.
func HasCapability(operationID string, cap Capability) bool {
	caps := OperationCapabilities[operationID]
	for _, c := range caps {
		if c == cap {
			return true
		}
	}
	return false
}

// IsReadOnly returns true if an operation only has read capability.
func IsReadOnly(operationID string) bool {
	caps := OperationCapabilities[operationID]
	if len(caps) == 0 {
		return false
	}
	for _, c := range caps {
		if c != CapRead && c != CapAnalytics && c != CapStream {
			return false
		}
	}
	return true
}

// RequiresAdmin returns true if an operation requires admin capability.
func RequiresAdmin(operationID string) bool {
	return HasCapability(operationID, CapAdmin)
}

// IsEvaluation returns true if an operation is an evaluation operation.
func IsEvaluation(operationID string) bool {
	return HasCapability(operationID, CapEvaluate)
}

// SupportsStreaming returns true if an operation supports streaming.
func SupportsStreaming(operationID string) bool {
	return HasCapability(operationID, CapStream)
}

// GetOperationsByCapability returns all operations that have a specific capability.
func GetOperationsByCapability(cap Capability) []string {
	var ops []string
	for op, caps := range OperationCapabilities {
		for _, c := range caps {
			if c == cap {
				ops = append(ops, op)
				break
			}
		}
	}
	return ops
}
