// Package ax provides Agent Experience (AX) metadata for the Opik API.
//
// This package is generated by ax-spec from x-ax-* OpenAPI extensions and API
// discovery. It provides:
//
//   - Error code constants for machine-readable error handling
//   - Retry policies indicating which operations are safe to retry
//   - Capability mappings for operation introspection
//   - Required field validation for request bodies
//
// Error Handling Example:
//
//	import "github.com/plexusone/opik-go/ax"
//
//	trace, err := client.GetTrace(ctx, traceID)
//	if err != nil {
//	    apiErr := opik.ParseAPIError(err)
//	    if apiErr != nil && ax.IsErrorCode(apiErr, ax.ErrTraceNotFound) {
//	        // Handle specific error
//	    }
//	}
//
// Retry Policy Example:
//
//	if ax.IsRetryable("findTraces") {
//	    // Safe to implement automatic retry
//	}
//
// The Opik API is used for LLM observability, tracing, and evaluation.
// Machine-readable error codes enable AI agents to reliably integrate
// with observability pipelines.
package ax
