// Code generated by ax-spec. DO NOT EDIT.

package ax

import "strings"

// Error codes for the Opik API.
// These codes enable machine-readable error handling for AI agents
// working with LLM observability and tracing.
const (
	// ErrTraceNotFound indicates the requested trace was not found.
	ErrTraceNotFound = "TRACE_NOT_FOUND"

	// ErrSpanNotFound indicates the requested span was not found.
	ErrSpanNotFound = "SPAN_NOT_FOUND"

	// ErrDatasetNotFound indicates the requested dataset was not found.
	ErrDatasetNotFound = "DATASET_NOT_FOUND"

	// ErrExperimentNotFound indicates the requested experiment was not found.
	ErrExperimentNotFound = "EXPERIMENT_NOT_FOUND"

	// ErrPromptNotFound indicates the requested prompt was not found.
	ErrPromptNotFound = "PROMPT_NOT_FOUND"

	// ErrProjectNotFound indicates the requested project was not found.
	ErrProjectNotFound = "PROJECT_NOT_FOUND"

	// ErrFeedbackNotFound indicates the requested feedback was not found.
	ErrFeedbackNotFound = "FEEDBACK_NOT_FOUND"

	// ErrAttachmentNotFound indicates the requested attachment was not found.
	ErrAttachmentNotFound = "ATTACHMENT_NOT_FOUND"

	// ErrUnauthorized indicates authentication is required or failed.
	ErrUnauthorized = "UNAUTHORIZED"

	// ErrForbidden indicates the user lacks permission for the operation.
	ErrForbidden = "FORBIDDEN"

	// ErrInvalidInput indicates the request input validation failed.
	ErrInvalidInput = "INVALID_INPUT"

	// ErrConflict indicates a resource conflict (e.g., duplicate name).
	ErrConflict = "CONFLICT"

	// ErrRateLimited indicates the request was rate limited.
	ErrRateLimited = "RATE_LIMITED"

	// ErrInternalError indicates an internal server error.
	ErrInternalError = "INTERNAL_ERROR"

	// ErrWorkspaceNotFound indicates the workspace was not found.
	ErrWorkspaceNotFound = "WORKSPACE_NOT_FOUND"

	// ErrEvaluatorNotFound indicates the evaluator was not found.
	ErrEvaluatorNotFound = "EVALUATOR_NOT_FOUND"

	// ErrAlertNotFound indicates the alert was not found.
	ErrAlertNotFound = "ALERT_NOT_FOUND"

	// ErrQueueNotFound indicates the annotation queue was not found.
	ErrQueueNotFound = "QUEUE_NOT_FOUND"

	// ErrDashboardNotFound indicates the dashboard was not found.
	ErrDashboardNotFound = "DASHBOARD_NOT_FOUND"
)

// AllErrorCodes contains all known Opik API error codes.
var AllErrorCodes = []string{
	ErrTraceNotFound,
	ErrSpanNotFound,
	ErrDatasetNotFound,
	ErrExperimentNotFound,
	ErrPromptNotFound,
	ErrProjectNotFound,
	ErrFeedbackNotFound,
	ErrAttachmentNotFound,
	ErrUnauthorized,
	ErrForbidden,
	ErrInvalidInput,
	ErrConflict,
	ErrRateLimited,
	ErrInternalError,
	ErrWorkspaceNotFound,
	ErrEvaluatorNotFound,
	ErrAlertNotFound,
	ErrQueueNotFound,
	ErrDashboardNotFound,
}

// ErrorCodeInfo provides metadata about an error code.
type ErrorCodeInfo struct {
	Code        string
	Description string
	Retryable   bool
	Category    string
	HTTPStatus  int
}

// ErrorCodeMetadata maps error codes to their metadata.
var ErrorCodeMetadata = map[string]ErrorCodeInfo{
	ErrTraceNotFound: {
		Code:        ErrTraceNotFound,
		Description: "The requested trace was not found",
		Retryable:   false,
		Category:    "not_found",
		HTTPStatus:  404,
	},
	ErrSpanNotFound: {
		Code:        ErrSpanNotFound,
		Description: "The requested span was not found",
		Retryable:   false,
		Category:    "not_found",
		HTTPStatus:  404,
	},
	ErrDatasetNotFound: {
		Code:        ErrDatasetNotFound,
		Description: "The requested dataset was not found",
		Retryable:   false,
		Category:    "not_found",
		HTTPStatus:  404,
	},
	ErrExperimentNotFound: {
		Code:        ErrExperimentNotFound,
		Description: "The requested experiment was not found",
		Retryable:   false,
		Category:    "not_found",
		HTTPStatus:  404,
	},
	ErrPromptNotFound: {
		Code:        ErrPromptNotFound,
		Description: "The requested prompt was not found",
		Retryable:   false,
		Category:    "not_found",
		HTTPStatus:  404,
	},
	ErrProjectNotFound: {
		Code:        ErrProjectNotFound,
		Description: "The requested project was not found",
		Retryable:   false,
		Category:    "not_found",
		HTTPStatus:  404,
	},
	ErrFeedbackNotFound: {
		Code:        ErrFeedbackNotFound,
		Description: "The requested feedback was not found",
		Retryable:   false,
		Category:    "not_found",
		HTTPStatus:  404,
	},
	ErrAttachmentNotFound: {
		Code:        ErrAttachmentNotFound,
		Description: "The requested attachment was not found",
		Retryable:   false,
		Category:    "not_found",
		HTTPStatus:  404,
	},
	ErrUnauthorized: {
		Code:        ErrUnauthorized,
		Description: "Authentication is required or failed",
		Retryable:   false,
		Category:    "auth",
		HTTPStatus:  401,
	},
	ErrForbidden: {
		Code:        ErrForbidden,
		Description: "User lacks permission for this operation",
		Retryable:   false,
		Category:    "auth",
		HTTPStatus:  403,
	},
	ErrInvalidInput: {
		Code:        ErrInvalidInput,
		Description: "Request input validation failed",
		Retryable:   false,
		Category:    "validation",
		HTTPStatus:  400,
	},
	ErrConflict: {
		Code:        ErrConflict,
		Description: "Resource conflict (e.g., duplicate name)",
		Retryable:   false,
		Category:    "conflict",
		HTTPStatus:  409,
	},
	ErrRateLimited: {
		Code:        ErrRateLimited,
		Description: "Request was rate limited",
		Retryable:   true,
		Category:    "rate_limit",
		HTTPStatus:  429,
	},
	ErrInternalError: {
		Code:        ErrInternalError,
		Description: "Internal server error",
		Retryable:   true,
		Category:    "server",
		HTTPStatus:  500,
	},
	ErrWorkspaceNotFound: {
		Code:        ErrWorkspaceNotFound,
		Description: "The workspace was not found",
		Retryable:   false,
		Category:    "not_found",
		HTTPStatus:  404,
	},
	ErrEvaluatorNotFound: {
		Code:        ErrEvaluatorNotFound,
		Description: "The evaluator was not found",
		Retryable:   false,
		Category:    "not_found",
		HTTPStatus:  404,
	},
	ErrAlertNotFound: {
		Code:        ErrAlertNotFound,
		Description: "The alert was not found",
		Retryable:   false,
		Category:    "not_found",
		HTTPStatus:  404,
	},
	ErrQueueNotFound: {
		Code:        ErrQueueNotFound,
		Description: "The annotation queue was not found",
		Retryable:   false,
		Category:    "not_found",
		HTTPStatus:  404,
	},
	ErrDashboardNotFound: {
		Code:        ErrDashboardNotFound,
		Description: "The dashboard was not found",
		Retryable:   false,
		Category:    "not_found",
		HTTPStatus:  404,
	},
}

// IsErrorCode checks if an error contains the specified AX error code.
// It works with any error type by checking if the error string contains the code.
func IsErrorCode(err error, code string) bool {
	if err == nil {
		return false
	}
	return strings.Contains(err.Error(), code)
}

// ContainsErrorCode extracts the AX error code from an error, if present.
// Returns the matching code and true if found, empty string and false otherwise.
func ContainsErrorCode(err error) (string, bool) {
	if err == nil {
		return "", false
	}
	errStr := err.Error()
	for _, code := range AllErrorCodes {
		if strings.Contains(errStr, code) {
			return code, true
		}
	}
	return "", false
}

// GetErrorInfo returns metadata about an error code.
// Returns nil if the code is not recognized.
func GetErrorInfo(code string) *ErrorCodeInfo {
	if info, ok := ErrorCodeMetadata[code]; ok {
		return &info
	}
	return nil
}

// IsAuthError returns true if the error code indicates an authentication/authorization issue.
func IsAuthError(code string) bool {
	info := GetErrorInfo(code)
	return info != nil && info.Category == "auth"
}

// IsNotFoundError returns true if the error code indicates a resource was not found.
func IsNotFoundError(code string) bool {
	info := GetErrorInfo(code)
	return info != nil && info.Category == "not_found"
}

// IsValidationError returns true if the error code indicates a validation failure.
func IsValidationError(code string) bool {
	info := GetErrorInfo(code)
	return info != nil && info.Category == "validation"
}

// IsConflictError returns true if the error code indicates a resource conflict.
func IsConflictError(code string) bool {
	info := GetErrorInfo(code)
	return info != nil && info.Category == "conflict"
}

// IsRetryableError returns true if the error code indicates a retryable error.
func IsRetryableError(code string) bool {
	info := GetErrorInfo(code)
	return info != nil && info.Retryable
}

// ErrorCodeForHTTPStatus returns a likely error code for an HTTP status.
// This is a heuristic when no specific error code is available.
func ErrorCodeForHTTPStatus(status int) string {
	switch status {
	case 400:
		return ErrInvalidInput
	case 401:
		return ErrUnauthorized
	case 403:
		return ErrForbidden
	case 404:
		return "" // Could be many things
	case 409:
		return ErrConflict
	case 429:
		return ErrRateLimited
	case 500, 502, 503, 504:
		return ErrInternalError
	default:
		return ""
	}
}
