// Code generated by ax-spec. DO NOT EDIT.

package ax

// RetryPolicy maps operation IDs to their retry safety.
// true = safe to retry automatically (idempotent reads)
// false = not safe to retry without user confirmation (may cause duplicates)
//
// This information is derived from:
//   - HTTP method (GET/HEAD/OPTIONS are generally safe)
//   - Operation semantics (create operations are not safe)
//   - x-ax-retryable extensions when present
var RetryPolicy = map[string]bool{
	// BI/Analytics operations (GET - safe)
	"getDatasetBiInfo":           true,
	"getExperimentBiInfo":        true,
	"getSpansBiInfo":             true,
	"getSpansCountForWorkspaces": true,
	"getTracesBiInfo":            true,
	"getTracesCountForWorkspaces": true,

	// Alert operations
	"findAlerts":       true,
	"createAlert":      false,
	"deleteAlertBatch": false,
	"getAlertById":     true,
	"updateAlert":      false,
	"getWebhookExamples": true,
	"testWebhook":      false,

	// Annotation Queue operations
	"addItemsToAnnotationQueue":    false,
	"findAnnotationQueues":         true,
	"createAnnotationQueue":        false,
	"createAnnotationQueueBatch":   false,
	"deleteAnnotationQueueBatch":   false,
	"getAnnotationQueueById":       true,
	"updateAnnotationQueue":        false,
	"removeItemsFromAnnotationQueue": false,

	// Attachment operations
	"attachmentList":          true,
	"completeMultiPartUpload": false,
	"deleteAttachments":       false,
	"downloadAttachment":      true,
	"startMultiPartUpload":    false,
	"uploadAttachment":        false,

	// Auth/Access operations
	"checkAccess":     true,
	"getWorkspaceName": true,

	// Evaluator operations
	"findEvaluators":                    true,
	"createAutomationRuleEvaluator":     false,
	"deleteAutomationRuleEvaluatorBatch": false,
	"getEvaluatorById":                  true,
	"updateAutomationRuleEvaluator":     false,
	"getEvaluatorLogsById":              true,

	// Chat Completions
	"createChatCompletions": false,

	// Dashboard operations
	"findDashboards":       true,
	"createDashboard":      false,
	"getDashboardById":     true,
	"deleteDashboard":      false,
	"updateDashboard":      false,
	"deleteDashboardsBatch": false,

	// Dataset operations
	"batchUpdateDatasetItems":           false,
	"findDatasets":                      true,
	"createDataset":                     false,
	"createOrUpdateDatasetItems":        false,
	"createDatasetItemsFromCsv":         false,
	"createDatasetItemsFromSpans":       false,
	"createDatasetItemsFromTraces":      false,
	"getDatasetById":                    true,
	"updateDataset":                     false,
	"deleteDataset":                     false,
	"deleteDatasetByName":               false,
	"deleteDatasetItems":                false,
	"deleteDatasetsBatch":               false,
	"expandDataset":                     false,
	"findDatasetItemsWithExperimentItems": true,
	"getDatasetByIdentifier":            true,
	"getDatasetExperimentItemsStats":    true,
	"getDatasetItemById":                true,
	"patchDatasetItem":                  false,
	"getDatasetItems":                   true,
	"getDatasetItemsOutputColumns":      true,
	"streamDatasetItems":                true,
	"compareDatasetVersions":            true,
	"createVersionTag":                  false,
	"listDatasetVersions":               true,
	"createDatasetVersion":              false,
	"deleteVersionTag":                  false,
	"restoreDatasetVersion":             false,
	"updateDatasetVersion":              false,

	// Experiment operations
	"findExperiments":                  true,
	"createExperiment":                 false,
	"createExperimentItems":            false,
	"deleteExperimentItems":            false,
	"deleteExperimentsById":            false,
	"experimentItemsBulk":              false,
	"findFeedbackScoreNames":           true,
	"findExperimentGroups":             true,
	"findExperimentGroupsAggregations": true,
	"finishExperiments":                false,
	"getExperimentById":                true,
	"updateExperiment":                 false,
	"getExperimentItemById":            true,
	"streamExperimentItems":            true,
	"streamExperiments":                true,

	// Feedback Definition operations
	"findFeedbackDefinitions":       true,
	"createFeedbackDefinition":      false,
	"getFeedbackDefinitionById":     true,
	"updateFeedbackDefinition":      false,
	"deleteFeedbackDefinitionById":  false,
	"deleteFeedbackDefinitionsBatch": false,

	// Guardrails
	"createGuardrails": false,

	// LLM Provider operations
	"deleteLlmProviderApiKeysBatch": false,
	"findLlmProviderKeys":           true,
	"storeLlmProviderApiKey":        false,
	"getLlmProviderApiKeyById":      true,
	"updateLlmProviderApiKey":       false,

	// LLM Evaluation operations
	"evaluateSpans":   false,
	"evaluateThreads": false,
	"evaluateTraces":  false,

	// OpenTelemetry
	"receiveProtobufTraces": false,

	// Optimization operations
	"cancelStudioOptimizations": false,
	"findOptimizations":         true,
	"upsertOptimization":        false,
	"createOptimization":        false,
	"deleteOptimizationsById":   false,
	"findStudioOptimizations":   true,
	"getOptimizationById":       true,
	"updateOptimizationsById":   false,
	"getStudioOptimizationById": true,
	"getStudioOptimizationLogs": true,

	// Project operations
	"findProjects":                    true,
	"createProject":                   false,
	"getProjectById":                  true,
	"deleteProjectById":               false,
	"updateProject":                   false,
	"deleteProjectsBatch":             false,
	"findFeedbackScoreNamesByProjectIds": true,
	"getProjectMetrics":               true,
	"getProjectStats":                 true,
	"retrieveProject":                 true,

	// Prompt operations
	"getPrompts":            true,
	"createPrompt":          false,
	"createPromptVersion":   false,
	"updatePromptVersions":  false,
	"getPromptById":         true,
	"updatePrompt":          false,
	"deletePrompt":          false,
	"deletePromptsBatch":    false,
	"getPromptVersionById":  true,
	"getPromptVersions":     true,
	"restorePromptVersion":  false,
	"retrievePromptVersion": true,

	// Service operations
	"getServiceToggles": true,

	// Span operations
	"addSpanComment":          false,
	"addSpanFeedbackScore":    false,
	"createSpans":             false,
	"batchUpdateSpans":        false,
	"getSpansByProject":       true,
	"createSpan":              false,
	"getSpanById":             true,
	"deleteSpanById":          false,
	"updateSpan":              false,
	"deleteSpanComments":      false,
	"deleteSpanFeedbackScore": false,
	"findFeedbackScoreNames_1": true,
	"getSpanComment":          true,
	"getSpanStats":            true,
	"scoreBatchOfSpans":       false,
	"searchSpans":             true,
	"updateSpanComment":       false,

	// Thread operations
	"addThreadComment":                   false,
	"closeTraceThread":                   false,
	"deleteThreadComments":               false,
	"deleteThreadFeedbackScores":         false,
	"deleteTraceThreads":                 false,
	"findTraceThreadsFeedbackScoreNames": true,
	"getThreadComment":                   true,
	"getTraceThreadStats":                true,
	"getTraceThread":                     true,
	"getTraceThreads":                    true,
	"openTraceThread":                    false,
	"scoreBatchOfThreads":                false,
	"searchTraceThreads":                 true,
	"updateThread":                       false,
	"updateThreadComment":                false,

	// Trace operations
	"addTraceComment":           false,
	"addTraceFeedbackScore":     false,
	"createTraces":              false,
	"batchUpdateTraces":         false,
	"batchUpdateThreads":        false,
	"getTracesByProject":        true,
	"createTrace":               false,
	"getTraceById":              true,
	"deleteTraceById":           false,
	"updateTrace":               false,
	"deleteTraceComments":       false,
	"deleteTraceFeedbackScore":  false,
	"deleteTraces":              false,
	"findFeedbackScoreNames_2":  true,
	"getTraceStats":             true,
	"getTraceComment":           true,
	"scoreBatchOfTraces":        false,
	"searchTraces":              true,
	"updateTraceComment":        false,

	// Welcome wizard
	"getWelcomeWizardStatus": true,
	"submitWelcomeWizard":    false,

	// Workspace/Usage operations
	"costsSummary":                true,
	"getWorkspaceConfiguration":   true,
	"upsertWorkspaceConfiguration": false,
	"deleteWorkspaceConfiguration": false,
	"getCost":                     true,
	"getMetric":                   true,
	"metricsSummary":              true,

	// Redirect operations
	"datasetsRedirect":      true,
	"experimentsRedirect":   true,
	"optimizationsRedirect": true,
	"projectsRedirect":      true,

	// Health checks
	"isAlive": true,
	"version": true,
}

// IsRetryable returns whether an operation is safe to retry automatically.
// Operations not in the map default to false (not retryable).
func IsRetryable(operationID string) bool {
	retryable, ok := RetryPolicy[operationID]
	if !ok {
		return false
	}
	return retryable
}

// GetRetryableOperations returns all operation IDs that are safe to retry.
func GetRetryableOperations() []string {
	var ops []string
	for op, retryable := range RetryPolicy {
		if retryable {
			ops = append(ops, op)
		}
	}
	return ops
}

// GetNonRetryableOperations returns all operation IDs that are NOT safe to retry.
func GetNonRetryableOperations() []string {
	var ops []string
	for op, retryable := range RetryPolicy {
		if !retryable {
			ops = append(ops, op)
		}
	}
	return ops
}

// RetryableCount returns counts of retryable and non-retryable operations.
func RetryableCount() (retryable, nonRetryable int) {
	for _, r := range RetryPolicy {
		if r {
			retryable++
		} else {
			nonRetryable++
		}
	}
	return
}
