// Code generated by ax-spec. DO NOT EDIT.

package ax

// RequiredFields maps operation IDs to their required input fields.
// This is extracted from the OpenAPI specification's requestBody schema
// required fields, allowing pre-flight validation before making API calls.
var RequiredFields = map[string][]string{
	// Alert operations
	"createAlert": {"name", "notification"},
	"updateAlert": {"name", "notification"},

	// Annotation Queue operations
	"createAnnotationQueue":      {"name"},
	"createAnnotationQueueBatch": {"queues"},
	"updateAnnotationQueue":      {"name"},

	// Attachment operations
	"completeMultiPartUpload": {"file_name", "entity_type", "entity_id", "num_uploaded_parts"},
	"startMultiPartUpload":    {"file_name", "entity_type", "entity_id", "num_parts"},
	"uploadAttachment":        {"file", "entity_type", "entity_id"},

	// Evaluator operations
	"createAutomationRuleEvaluator": {"name", "code"},
	"updateAutomationRuleEvaluator": {"name", "code"},

	// Chat Completions
	"createChatCompletions": {"model", "messages"},

	// Dashboard operations
	"createDashboard": {"name"},
	"updateDashboard": {"name"},

	// Dataset operations
	"createDataset":                {"name"},
	"createOrUpdateDatasetItems":   {"items"},
	"createDatasetItemsFromCsv":    {"file"},
	"createDatasetItemsFromSpans":  {"span_ids"},
	"createDatasetItemsFromTraces": {"trace_ids"},
	"updateDataset":                {"name"},
	"createVersionTag":             {"tag_name"},
	"createDatasetVersion":         {"name"},
	"updateDatasetVersion":         {"name"},

	// Experiment operations
	"createExperiment":      {"dataset_name", "name"},
	"createExperimentItems": {"experiment_items"},
	"experimentItemsBulk":   {"experiment_items"},
	"updateExperiment":      {"name"},

	// Feedback Definition operations
	"createFeedbackDefinition": {"name", "type"},
	"updateFeedbackDefinition": {"name", "type"},

	// Guardrails
	"createGuardrails": {"project_name", "trace_id", "span_id"},

	// LLM Provider operations
	"storeLlmProviderApiKey":  {"provider", "api_key"},
	"updateLlmProviderApiKey": {"api_key"},

	// LLM Evaluation operations
	"evaluateSpans":   {"span_ids", "evaluator_ids"},
	"evaluateThreads": {"thread_ids", "evaluator_ids"},
	"evaluateTraces":  {"trace_ids", "evaluator_ids"},

	// Optimization operations
	"createOptimization": {"project_name", "name"},
	"upsertOptimization": {"project_name", "name"},

	// Project operations
	"createProject": {"name"},
	"updateProject": {"name"},

	// Prompt operations
	"createPrompt":        {"name", "template"},
	"createPromptVersion": {"template"},
	"updatePrompt":        {"name"},

	// Span operations
	"addSpanComment":       {"text"},
	"addSpanFeedbackScore": {"name", "value"},
	"createSpans":          {"spans"},
	"createSpan":           {"trace_id", "name"},
	"updateSpan":           {"trace_id"},
	"updateSpanComment":    {"text"},

	// Thread operations
	"addThreadComment":    {"text"},
	"updateThread":        {"name"},
	"updateThreadComment": {"text"},

	// Trace operations
	"addTraceComment":       {"text"},
	"addTraceFeedbackScore": {"name", "value"},
	"createTraces":          {"traces"},
	"createTrace":           {"name"},
	"updateTrace":           {"project_name"},
	"updateTraceComment":    {"text"},

	// Workspace operations
	"upsertWorkspaceConfiguration": {"config"},

	// Search operations
	"searchSpans":        {"filters"},
	"searchTraces":       {"filters"},
	"searchTraceThreads": {"filters"},
}

// GetRequiredFields returns the required fields for an operation.
// Returns nil if the operation has no required fields or is not found.
func GetRequiredFields(operationID string) []string {
	return RequiredFields[operationID]
}

// HasRequiredFields returns true if the operation has required fields.
func HasRequiredFields(operationID string) bool {
	fields := RequiredFields[operationID]
	return len(fields) > 0
}

// MissingFields checks which required fields are missing from a request.
// The provided map should contain the field names that are present.
// Returns a slice of missing field names.
func MissingFields(operationID string, presentFields map[string]bool) []string {
	required := RequiredFields[operationID]
	if len(required) == 0 {
		return nil
	}

	var missing []string
	for _, field := range required {
		if !presentFields[field] {
			missing = append(missing, field)
		}
	}
	return missing
}

// ValidateFields returns an error message if required fields are missing.
// Returns empty string if all required fields are present.
func ValidateFields(operationID string, presentFields map[string]bool) string {
	missing := MissingFields(operationID, presentFields)
	if len(missing) == 0 {
		return ""
	}

	if len(missing) == 1 {
		return "missing required field: " + missing[0]
	}

	result := "missing required fields: "
	for i, field := range missing {
		if i > 0 {
			result += ", "
		}
		result += field
	}
	return result
}

// OperationRequirements returns a summary of an operation's requirements.
type OperationRequirements struct {
	OperationID    string
	RequiredFields []string
	Retryable      bool
}

// GetOperationRequirements returns full requirements for an operation.
func GetOperationRequirements(operationID string) *OperationRequirements {
	return &OperationRequirements{
		OperationID:    operationID,
		RequiredFields: GetRequiredFields(operationID),
		Retryable:      IsRetryable(operationID),
	}
}
